Student.create!([
  {username: "15911702087", password: "24909X@Crgz", cookie: "JSESSIONID=19cce965-d655-4bce-835f-c1bdc490f0f2", law_score: 97.5, law_count: 1, math_score: 0.0, math_count: 0, chinese_score: 0.0, chinese_count: 0, social_score: nil, social_count: 0},
  {username: "15094106872", password: "271237@Crgz", cookie: "JSESSIONID=13050ccb-6b67-4794-999b-876655e0e4d8", law_score: nil, law_count: 0, math_score: nil, math_count: 0, chinese_score: nil, chinese_count: 0, social_score: nil, social_count: 0},
  {username: "13913933727", password: "221619@Crgz", cookie: "JSESSIONID=f9ae82f5-8efa-436d-aea9-022cc94ffc84", law_score: nil, law_count: 0, math_score: nil, math_count: 0, chinese_score: nil, chinese_count: 0, social_score: nil, social_count: 0},
  {username: "18961620956", password: "145666@Crgz", cookie: "JSESSIONID=1e992354-7482-4e6a-92b8-62dbda08d5e0", law_score: nil, law_count: 0, math_score: nil, math_count: 0, chinese_score: nil, chinese_count: 0, social_score: nil, social_count: 0}
])
QuestionBank.create!([
  {paper_id: "12", exam_question_id: "1897", answer: "B", question_title: "依次填入下面各句横线上的词语，最恰当的一组是 （ &nbsp; &nbsp;）（1）近年来，由于各级政府加大了治理中小学乱收费现象的工作力度，多数地区乱收费的发展势头得到了有效 _____。（2）小说中的典型形象虽然有生活_____的，但仍属于虚构的形象。（3）出了差错，要多从自己身上找原因，不要老是埋怨别人，____责任。（4）正确与错误之间的____,有时并不是一下子就能分清的。"},
  {paper_id: "15", exam_question_id: "2084", answer: "C", question_title: "中国共产党人的初心和使命，就是为中国人民（ &nbsp; ），为中华民族（ &nbsp; ）。这个初心和使命是激励中国共产党人不断前进的根本动力。"},
  {paper_id: "13", exam_question_id: "2252", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eddaede0045.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2184", answer: "D", question_title: "尊老爱幼，尊重妇女，对待老人、儿童、残疾人员，特别予以尊重、照顾、爱护和帮助，这是社会公德中（ &nbsp; &nbsp;）的要求。"},
  {paper_id: "13", exam_question_id: "2253", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec821aa0013.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2187", answer: "C", question_title: "在2l世纪全面建设小康社会的今天，勤俭持家富有新的涵义。下列观点符合勤俭持家新涵义的是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1908", answer: "D", question_title: "下列名著、作者、人物搭配有误的一项是 （ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2085", answer: "D", question_title: "“中国生态文明建设进入了快车道，天更蓝、山更绿、水更清将不断展现在世人面前。”这句话体现的发展理念是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2192", answer: "A", question_title: "杨先生外出时忘了关好水龙头,导致房间积水并渗入楼下静静家,使得墙皮发霉,客厅沙发、电器浸水毁坏。静静要求杨先生恢复原状并赔偿损失,遭到拒绝。对此,静静可以（ &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2090", answer: "D", question_title: "<p style=\"text-align: left;\">中国共产党为什么能，中国特色社会主义为什么好，归根到底是马克思主义行，是（ &nbsp; ）的马克思主义行。"},
  {paper_id: "13", exam_question_id: "2256", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edb1b2c0034.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1909", answer: "A", question_title: "《红楼梦》小说中林黛玉的老师（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2096", answer: "A", question_title: "“一个篱笆三个桩，一个好汉三个帮”，说的是就业者要具备（ &nbsp;）的优秀职业道德。"},
  {paper_id: "14", exam_question_id: "2193", answer: "C", question_title: "饲养动物，干扰他人正常生活的行为属于（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2258", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edea7a2004c.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1916", answer: "C", question_title: "下列各句中不是谈学习态度的是：（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2099", answer: "D", question_title: "（ &nbsp; ）是我国社会保障体系中最基本的内容。"},
  {paper_id: "14", exam_question_id: "2201", answer: "A", question_title: "我国法律赋予公民的参加国家管理的最基本政治权利是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2264", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee06f4a005d.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1917", answer: "C", question_title: "<p style=\"text-align: justify;\">王先生的QQ签名档最近改成了“庆祝弄璋之喜”，王先生近来的喜事是： ( &nbsp;)"},
  {paper_id: "15", exam_question_id: "2101", answer: "A", question_title: "实现农业和农村的现代化，建设社会主义新农村，全面落实科学发展观，关键就是要（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2204", answer: "B", question_title: "赈灾救荒、捐资助学、义务献血等行为是反映（ &nbsp; ）的新型人际关系现象。"},
  {paper_id: "15", exam_question_id: "2111", answer: "D", question_title: "香港回归祖国是在（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1930", answer: "B", question_title: "下列诗句中描写秋天景色的是（ &nbsp; ）句"},
  {paper_id: "13", exam_question_id: "2267", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee176660066.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1936", answer: "C", question_title: "依次填入下列横线处的词语，最恰当的一项是（ &nbsp; ）我们_______读什么书，______必须认真地读，______了解书的内容，______ 要通过书的内容去了解其反映的时代和社会，否则，就不能算读懂读透。"},
  {paper_id: "14", exam_question_id: "2212", answer: "D", question_title: "下列是某超市的四个广告牌，其中内容合法的是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2272", answer: "D", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee31f140077.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2113", answer: "A", question_title: "鸦片战争给中国带来的最大影响是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2220", answer: "A", question_title: "公民最基本的权利、公民享有其他一切权利的先决条件是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2277", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee497a50087.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1940", answer: "D", question_title: "下列表述有错误的一项是（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2118", answer: "C", question_title: "十一届三中全会后，率先进行经济体制改革的是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2467", answer: "B", question_title: "黄某、武某、李某系老乡，某一天三人聚餐喝了不少酒，餐后约定以路灯为目标比赛谁投掷石块最准，毁坏了几盏路灯。这三人的行为属于（&nbsp;）的违法行为。"},
  {paper_id: "13", exam_question_id: "2279", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee51099008c.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2119", answer: "C", question_title: "第一次世界大战的性质是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1943", answer: "B", question_title: "选出对下列各句所用修辞手法的判断及其表达效果的分析正确的一项（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2471", answer: "B", question_title: "根据刑罚的规定，我国刑罚的种类分为（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2283", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee64c500097.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2358", answer: "A", question_title: "和平共处五项原则的首次提出是在。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "1950", answer: "B", question_title: "下列加【】括号的成语使用不妥当的一项是（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2489", answer: "A", question_title: "下列情形中劳动者可以随时通知用人单位解除劳动合同的是（  &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2380", answer: "C", question_title: "（&nbsp;）的创立是中国古代地方行政制度的重大变革，是中国省制的开端。"},
  {paper_id: "13", exam_question_id: "2285", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee6a4270098.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1955", answer: "A", question_title: "每首诗有四句，每句有五个字的古诗体裁叫（ &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2423", answer: "A", question_title: "中国人最早摄制的电影是1905年的（&nbsp;）。"},
  {paper_id: "14", exam_question_id: "2490", answer: "B", question_title: "某村三个农民与村委会坚定了20亩鱼塘承包合同，承包期5年，当年塘鱼大丰收，人均获利约5万元。个别村干部眼红想毁约，三个农民应该（ &nbsp;  ）。"},
  {paper_id: "13", exam_question_id: "2287", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee7f73300a0.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1958", answer: "B", question_title: "<p style=\"text-align: justify;\">子在川上曰：“逝者如斯夫!不舍昼夜。”其中“逝者”的意思是指 ( &nbsp; ) "},
  {paper_id: "15", exam_question_id: "2429", answer: "A", question_title: "下列有关浙江省的各地的特色产业发展对应正确的是（  &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2497", answer: "A", question_title: "下列案例与处罚类别对应正确的是（ &nbsp;  ）"},
  {paper_id: "13", exam_question_id: "2292", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee95c6300ac.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1959", answer: "A", question_title: "“独在异乡为异客，每逢佳节倍思亲”是 ( &nbsp; &nbsp;) 的诗句。 "},
  {paper_id: "15", exam_question_id: "2443", answer: "A", question_title: "改革开放后，中国农村最早实行农村经济体制改革的省份是（ &nbsp;  ）"},
  {paper_id: "14", exam_question_id: "2498", answer: "D", question_title: "中国共产党的伟大建党精神就是：坚持真理、坚守理想，（ &nbsp; ）、担当使命，不怕牺牲、英勇斗争，对党忠诚、（&nbsp;   ）。它是中国共产党的精神之源。"},
  {paper_id: "13", exam_question_id: "2299", answer: "C", question_title: "<p>下列各对角中，终边相同的是 ( &nbsp; &nbsp; &nbsp; )</p>"},
  {paper_id: "12", exam_question_id: "1973", answer: "B", question_title: "下列各组中的加括号的词，读音全相同的一项是（ &nbsp; &nbsp;）"},
  {paper_id: "15", exam_question_id: "2124", answer: "B,D", question_title: "党的二十大报告指出，五年来，我们党团结带领人民，（ &nbsp; &nbsp;），推动党和国家事业取得举世瞩目的重大成就。"},
  {paper_id: "14", exam_question_id: "2502", answer: "D", question_title: "郭某向朋友李某借钱，逾期未还，李某多次催促无果，遂将郭某诉至人民法院。人民法院判决郭某偿还本金及利息。对此，下列分析正确的是（  &nbsp;  ）"},
  {paper_id: "12", exam_question_id: "1980", answer: "A", question_title: "对下列各句修辞方法的判断有误的一项是（ &nbsp; ）"},
  {paper_id: "13", exam_question_id: "2528", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee9ae8d00ae.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2125", answer: "A,B,C,D", question_title: "党的二十大指出，前进道路上，必须牢牢把握以下重大原则：（ &nbsp; &nbsp;）、坚持发扬斗争精神。"},
  {paper_id: "14", exam_question_id: "2227", answer: "A,B,C", question_title: "选举权和被选举权是公民的一项基本政治权利。在我国，公民享有选举权和被选举权的基本条件是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1987", answer: "A", question_title: "选出下列各组语句中句意明确、没有语病的一句（ &nbsp; &nbsp;）"},
  {paper_id: "13", exam_question_id: "2245", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec66e7b000b.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2128", answer: "B,C,D", question_title: "党的二十大报告指出，我们要健全人民当家作主制度体系，扩大人民有序政治参与，保证人民依法实行（ &nbsp; &nbsp;）、民主管理、民主监督，发挥人民群众积极性、主动性、创造性，巩固和发展生动活泼、安定团结的政治局面。"},
  {paper_id: "12", exam_question_id: "2006", answer: "B", question_title: "《西游记》中的火焰山位于（ &nbsp; &nbsp;）"},
  {paper_id: "13", exam_question_id: "2246", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec6a3c7000c.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2229", answer: "A,B,D", question_title: "以下属于治安管理处罚种类的（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "2010", answer: "A", question_title: "在小说《三国演义》中，下列事件中关云长不可能参加的是（ &nbsp; &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2133", answer: "B,A,C", question_title: "选择投资方式必须要考虑的因素有（ &nbsp; &nbsp;）。"},
  {paper_id: "13", exam_question_id: "2306", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ecda39a0026.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2230", answer: "A,B,C", question_title: "下列属于结婚的法定条件的是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "2325", answer: "A", question_title: "课文《红楼梦（节选）》是（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2139", answer: "A,C", question_title: "下列体现公民享有民主决策权的是（ &nbsp; &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2231", answer: "A,B,C", question_title: "《劳动法》明确规定劳动者应该享有的基本权利包括（ &nbsp; &nbsp;）。"},
  {paper_id: "13", exam_question_id: "2308", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ecafde20021.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2140", answer: "A,C,D", question_title: "下列属于公民监督国家机关和国家工作人员的权利是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "2354", answer: "A", question_title: "《假如生活欺骗了你》这首诗成为脍炙人口的名篇，对其原因分析不正确的一项是（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2232", answer: "B,C", question_title: "互联网已经深刻影响我们的生活，在网络上交朋友，发祝福、抢红包、学习、问医、购物……我们越来越离不开网络。但同时，网络诈骗、网络售假、网银被盗等也随之出现。对此我们应该（ &nbsp; &nbsp;）。"},
  {paper_id: "13", exam_question_id: "2310", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ed970c7002d.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2233", answer: "A,B,C", question_title: "遵纪守法的基本要求包括（ &nbsp; &nbsp;）三个方面。"},
  {paper_id: "15", exam_question_id: "2142", answer: "A,C", question_title: "当前，做好我国的宗教工作，必须坚持党的宗教工作基本方针，全面贯彻党的宗教政策。全面贯彻党的宗教政策要（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "2356", answer: "A", question_title: "下列对《水调歌头》赏析不正确的一项是：（&nbsp;）"},
  {paper_id: "13", exam_question_id: "2312", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ecb57d70023.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2468", answer: "ABD", question_title: "下列属于迷信活动的是（   &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2359", answer: "D", question_title: "下列词语中没有错别字的是（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2510", answer: "ABD", question_title: "“时代楷模”钱海军从事电力服务工作30余年，长期无偿帮扶他人，开发志愿服务云平台发起“千户万灯”活动，使光明照亮雪域高原、偏远山区。这生动诠释了"},
  {paper_id: "13", exam_question_id: "2318", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec9d926001c.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2478", answer: "BCD", question_title: "党的十八届五中全会提出，要全面实施一对夫妇可生育两个孩子政策。对此，下列理解中正确的观点是（  &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2511", answer: "AD", question_title: "抖音的出现，让许多普通人通过展示自己的才艺活跃了生活，但也有一些人借这个平台传播不当言论。这反映了（  &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2362", answer: "C", question_title: "下列词语中没有错别字的是 （&nbsp; &nbsp;）"},
  {paper_id: "13", exam_question_id: "2320", answer: "B", question_title: "空间不同的三点确定一个平面 （ &nbsp; &nbsp;）"},
  {paper_id: "15", exam_question_id: "2484", answer: "AD", question_title: "属于我国自然风光旅游资源的有（   &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2516", answer: "ACD", question_title: "下列同违法犯罪行为作斗争的方法可取的有（ &nbsp;   ）。"},
  {paper_id: "12", exam_question_id: "2368", answer: "C", question_title: "下列成语正确的一项是（&nbsp;&nbsp;）"},
  {paper_id: "13", exam_question_id: "2321", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eca46ad001e.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2051", answer: "A", question_title: "在日常生活中误收假币，不应再使用，应上缴当地银行或公安机关。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2520", answer: "ACD", question_title: "随着我国征信系统的成熟，如今个人征信已经覆盖到生活的方方面面。为了保持良好的个人信用记录，下列做法正确的是（  &nbsp;  ）。"},
  {paper_id: "13", exam_question_id: "2322", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eca6f72001f.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "2369", answer: "C", question_title: "下列成语正确的一项是 （ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2053", answer: "B", question_title: "我国社会保障体系中的社会保险，是由劳动者自己自愿实施的。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2143", answer: "A", question_title: "道德是人们共同生活及其行为的准则和规范。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2373", answer: "C", question_title: "选出不是比喻句的一项（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2055", answer: "A", question_title: "以家庭承包经营为基础、统分结合的双层经营体制，是党的农村政策的基石。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2154", answer: "A", question_title: "办事公道的核心是要克服私心、正直无私。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2071", answer: "B", question_title: "公元后221年，秦灭六国，统一了中国。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2377", answer: "A", question_title: "给下面一段话的横线上，选出一项最佳比喻句。（&nbsp;）核桃林散发出苹果般的清香，油润的叶子上，反射出点点灯光，警戒的战士游动着，刺刀尖上一明一暗的亮光，________ 。"},
  {paper_id: "14", exam_question_id: "2155", answer: "A", question_title: "尊老爱幼是中华民族传统的家庭美德，也是社会主义家庭美德的重要规范。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2076", answer: "B", question_title: "20世纪80年代初，为了解决香港问题，邓小平提出了“一国两制”的伟大构想。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2382", answer: "A", question_title: "对下列各句修辞方法判断有误的一项是（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2079", answer: "A", question_title: "联合国是当今世界规模最大、最有权威性、最有影响力的全球性组织。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2385", answer: "C", question_title: "下面句中没使用比喻的一项是（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2328", answer: "B", question_title: "英国工人爱迪生改良了蒸汽机。(&nbsp; )"},
  {paper_id: "12", exam_question_id: "2390", answer: "D", question_title: "对《蒹葭》赏析不当的一项是(&nbsp;)"},
  {paper_id: "15", exam_question_id: "2338", answer: "A", question_title: "农村到城市的人口迁移是发展中国家当前人口迁移的主要类型。（）"},
  {paper_id: "15", exam_question_id: "2339", answer: "A", question_title: "城乡和地区之间巨大的收入差距是促使我国人口大量流动的最根本的原因。（）"},
  {paper_id: "12", exam_question_id: "2016", answer: "A", question_title: "《假如生活欺骗了你》是俄国十九世纪浪漫主义诗人普希金的代表作（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2342", answer: "A", question_title: "在我国，年满18周岁的公民都具有选举权。（）"},
  {paper_id: "12", exam_question_id: "2027", answer: "B", question_title: "“海内存知己，天涯若比邻”出自王勃的《送杜少府之任蜀州》，这首诗的题材是山水诗。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2344", answer: "B", question_title: "塑料大棚中蔬菜、花卉的种植业属于自给农业。（）"},
  {paper_id: "12", exam_question_id: "2032", answer: "A", question_title: "借条、收据、领条，要写清钱物的金额、名称、规格、数量、质量（新旧、好坏程度）等款项。数字用大写，钱数末尾要加“整”。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2346", answer: "A", question_title: "中国特色社会主义事业总体布局是“五位一体”，战略布局是“四个全面”。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2038", answer: "A", question_title: "“恰似一江春水向东流”，是以水喻愁的名句，含蓄地显示出愁思的长流不断，无穷无尽。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2347", answer: "A", question_title: "根据国际标准，中国已经进入老龄化社会。（）"},
  {paper_id: "12", exam_question_id: "2395", answer: "B", question_title: "小说的要素是发生、发展、高潮、结局。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2348", answer: "B", question_title: "根据旅游资源的类型划分，北京故宫是自然资源旅游资源。（）"},
  {paper_id: "12", exam_question_id: "2398", answer: "A", question_title: "“问君能有几多愁？恰是一江春水向东流”是千古传诵的名句，它抒发了词人深重、难以遏制的愁绪。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2349", answer: "A", question_title: "国歌法规定，奏唱国歌时，在场人员应当肃立，举止庄重，不得有不尊重国歌行为。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2406", answer: "A", question_title: "《关雎》最后八句表达了希望与姑娘成婚的美好愿望。“琴瑟友之”、“钟鼓乐之”，是设想与姑娘结婚时鼓乐齐鸣的欢乐场面。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2407", answer: "A", question_title: "《诗经》中的许多诗歌都采用了赋中见兴的笔法，通过对眼前景物的描写，描绘出一个个优美的意境。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2413", answer: "A", question_title: "“三顾频烦天下计”指诸葛亮隐居隆中时，刘备曾三次登门拜访他，向他讨教统一天下的计策。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2422", answer: "B", question_title: "“但愿人长久，千里共婵娟”婵娟的含义是美女。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2156", answer: "B", question_title: "<p>“大丈夫做大事不拘小节”，所以做大事的人可以不遵守基本的公德。（ &nbsp; ）</p>"},
  {paper_id: "14", exam_question_id: "2158", answer: "A", question_title: "礼貌待人是人际交往最起码的要求。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2162", answer: "A", question_title: "任何公民不应只享受权利而不尽义务，也不会只尽义务而享受不到相应的权利。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2166", answer: "B", question_title: "在道路上发生了交通事故，只要双方同意，可以私了。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2168", answer: "B", question_title: "租赁房屋时，首先要考虑价格因素，没有出租人房屋所有权合法凭证无所谓。（ &nbsp; ） &nbsp;"},
  {paper_id: "14", exam_question_id: "2176", answer: "A", question_title: "社会保险的资金来源于企业、劳动者个人的缴费及政府的财政补贴。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2177", answer: "A", question_title: "养老保险是我国社会保险五大险种中最重要的险种之一。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2178", answer: "A", question_title: "用人单位违反工作时间和休息休假规定的，可以向劳动保障行政部门投诉。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2179", answer: "A", question_title: "法定休假日安排劳动者工作的，支付不低于劳动合同规定的劳动者本人日工资标准的300%的工资报酬。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2182", answer: "A", question_title: "我国一般民事诉讼的一般诉讼时效为3年。（ &nbsp; ） "},
  {paper_id: "14", exam_question_id: "2442", answer: "B", question_title: "下岗人员就是失业人员。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2448", answer: "A", question_title: "劳动者的大病医疗保险主要应由用人单位缴费。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "1894", answer: "B", question_title: "下列句子中没有错别字的一项是 （ &nbsp;）"},
  {paper_id: "13", exam_question_id: "2250", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edd3d7d0043.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2185", answer: "A", question_title: "（ &nbsp; ）反映的是公民个人与祖国、与社会的关系，是社会主义道德体系中最基本的规范。"},
  {paper_id: "12", exam_question_id: "1900", answer: "C", question_title: "如果你在接听电话时，碰到对方唠唠叨叨，废话连篇，正确的处理方法是 （ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2098", answer: "B", question_title: "在我国社会保障体系中，以革命烈士家属、复员退伍定人，残疾军人及其家属为主要对象的，属于（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2255", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eddd2870046.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1901", answer: "B", question_title: "有人仿造杜牧《清明》而写了这么一首诗：清明时节沙纷纷，路上行人满面尘。借问青山何处有，学童遥指盆景中。这首诗对什么现象进行了辛辣的讽刺？ （ &nbsp; &nbsp;） "},
  {paper_id: "15", exam_question_id: "2100", answer: "C", question_title: "中央一号文件以“三农”问题为主题,“三农”是指农村、农民和 （ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2194", answer: "D", question_title: "订立劳动合同必须符合（ &nbsp; &nbsp;）、平等自愿、协商一致的原则。"},
  {paper_id: "15", exam_question_id: "2102", answer: "D", question_title: "坚持最严格的耕地保护制度,层层落实责任,坚决守住（ &nbsp; ）亿亩耕地红线。"},
  {paper_id: "12", exam_question_id: "1905", answer: "A", question_title: "下列各句中，没有运用反问手法的一项是 （ &nbsp;）"},
  {paper_id: "13", exam_question_id: "2260", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edf7fa00055.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2198", answer: "A", question_title: "通常所说的“民告官”是指（ &nbsp; &nbsp;）。"},
  {paper_id: "15", exam_question_id: "2105", answer: "D", question_title: "佛教、伊斯兰教、天主教、基督教和我国土生土长的（ &nbsp; ）合称我国五大宗教。"},
  {paper_id: "13", exam_question_id: "2271", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee2f5fd0076.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2200", answer: "D", question_title: "公民刘某，住所地为A县，公民王某，住所地为B县，公民周某，住所地为C县。刘某以王某侵犯房屋的所有权为由向法院提起诉讼，周某则主张其才是房屋的真正主人。诉讼所涉及的房屋坐落于D县。那么拥有管辖权的法院是（ &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2110", answer: "C", question_title: "第一部《中华人民共和国宪法》诞生于（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1914", answer: "C", question_title: "下列句子中没有语病的一项是（ &nbsp; ）"},
  {paper_id: "13", exam_question_id: "2273", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee39130007c.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2202", answer: "A", question_title: "我国的根本大法是（ &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2117", answer: "D", question_title: "我国“一五”计划开始于（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1920", answer: "C", question_title: "下列哪一句诗描写的场景最适合采用水墨画来表现? ( &nbsp; &nbsp;)"},
  {paper_id: "13", exam_question_id: "2275", answer: "C", question_title: "<p style=\"text-align: left;\">陈老师每天采取“先慢跑，再慢走”的方式锻炼身体，慢跑和慢走都是匀速的，运动的距离（米）关于时间（分钟）的函数图像如图所示，他慢走的速度为（ &nbsp; &nbsp; &nbsp;）</p><p style=\"text-align: left;\"><img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edaa92c0033.png\" contenteditable=\"false\" style=\"font-size: 14px; max-width: 100%;\" width=\"291\" height=\"217.33\"/></p>"},
  {paper_id: "14", exam_question_id: "2210", answer: "D", question_title: "下列行为属于《中华人民共和国治安管理处罚法》规定的妨害公共安全的是（ &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1922", answer: "B", question_title: "文学史上被称作“小李杜”的分别是谁?( &nbsp; )"},
  {paper_id: "13", exam_question_id: "2282", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee627f20096.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1925", answer: "A", question_title: "《在水一方》的歌词来源于：( &nbsp; &nbsp;)"},
  {paper_id: "13", exam_question_id: "2286", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee75b22009a.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2120", answer: "B", question_title: "第二次世界大战发生的时间是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2218", answer: "D", question_title: "某市三位市民因在禁烟区吸烟，被依法行政拘留5日。对此，有人不理解：“吸烟是他们的自由和权利，为什么要处罚他们呢？”你会这样告诉他（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1929", answer: "C", question_title: "<p style=\"text-align: justify;\">“路漫漫其修远兮，吾将上下而求索”的作者是（ &nbsp;）"},
  {paper_id: "13", exam_question_id: "2289", answer: "C", question_title: "<p>下列命题正确的是（ &nbsp; &nbsp; &nbsp;）</p>"},
  {paper_id: "15", exam_question_id: "2367", answer: "C", question_title: "1955年的亚非万隆会议上，周恩来总理提出的外交方针促进了会议的圆满成功，这个外交方针是。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2470", answer: "A", question_title: "某企业规定职工上班期间上洗手间每次扣除五元工资，此规定侵犯了职工的（ &nbsp;  ）。"},
  {paper_id: "12", exam_question_id: "1931", answer: "A", question_title: "古代常用称谓代替年龄。请说出60岁的称谓：（ &nbsp; &nbsp;）"},
  {paper_id: "15", exam_question_id: "2371", answer: "B", question_title: "19世纪40年代，（  &nbsp; ）率先完成工业革命，成为世界上第一个工业国家。"},
  {paper_id: "13", exam_question_id: "2296", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eead19d00b7.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2495", answer: "A", question_title: "微信作为一种新兴的交流工具，走进了普通民众的生活。个人的言论自由得到了极大的发挥。但是微信自由的背后是公共责任与法律底线，这说明（   &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1937", answer: "C", question_title: "依次填入下面空格中的词语，恰当的一项是（ &nbsp;） &nbsp; <p style=\"text-indent: 18pt;\">①他的研究成果，在今天_____今后，都会大放异彩。<p style=\"text-indent: 18pt;\">②今天展出的工艺品，件件都很_____。<p style=\"text-indent: 18pt;\">③近几年，科技信息量_____地增加，科技知识每５年增长一倍。"},
  {paper_id: "15", exam_question_id: "2383", answer: "B", question_title: "《天路》这首歌赞美的是（&nbsp;）。"},
  {paper_id: "13", exam_question_id: "2300", answer: "D", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eebaeef00c0.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2496", answer: "D", question_title: "我国持续开展扫黑除恶专项斗争充分体现了我国（ &nbsp;  ）的发展思想和（  &nbsp;  ）的基本方略。"},
  {paper_id: "15", exam_question_id: "2428", answer: "C", question_title: "工厂正常生产，需要考虑的因素很多，其中社会经济因素包括交通运输条件、市场因素、当地投资环境，还包括（ &nbsp;  ）。"},
  {paper_id: "13", exam_question_id: "2301", answer: "D", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eebd5f100c1.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1944", answer: "B", question_title: "填入下列横线处的句子，表达效果最好的一句是：( &nbsp; ) 中外古今的诗人，常喜欢将珍珠与眼泪作比。阿拉伯的诗人说，牡蛎在海滩上赏月，天使的一滴眼泪，刚巧滴落在它心上，_____。"},
  {paper_id: "14", exam_question_id: "2504", answer: "C", question_title: "每年6月是我国的全民禁毒宣传月，公民依照《中华人民共和国禁毒法》，履行禁毒义务。开展全民禁毒宣传月活动有助于（  &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2432", answer: "A", question_title: "沟通中西陆上交通的丝绸之路经过的城市和地区有（&nbsp;   ）。"},
  {paper_id: "12", exam_question_id: "1946", answer: "B", question_title: "下列名著、作者、人物搭配有误的一项是（ &nbsp; ）"},
  {paper_id: "13", exam_question_id: "2302", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eece41e00c6.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2505", answer: "B", question_title: "法律让我们懂得在社会生活中可以做什么，应该做什么、不应该做什么，应该怎样做、不应该怎样做。法律为人们的行为提供一个模式、标准或方向。这说明我国法律具有（ &nbsp;  ）作用。"},
  {paper_id: "15", exam_question_id: "2441", answer: "C", question_title: "下列大众传媒出现的顺序是（  &nbsp; ）                                                                                                                                                                          ①电影   ②报纸    ③电视   ④互联网 "},
  {paper_id: "12", exam_question_id: "1947", answer: "B", question_title: "下面的莎士比亚作品中不属于他的“四大悲剧”的一项（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2507", answer: "C", question_title: "车主牛某某因停车位问题与另一车主王某某产生争执，并将王某某打伤。经鉴定，王某某左侧腰部的横突骨折损伤程度为轻伤一级。牛某某被人民法院依法判处管制2年。这一事件警示我们要（ &nbsp;  ）。\n<br>①认清危害，严格执法\n<br>②法不可违，尊法守法\n<br>③互敬互谅，友善待人\n<br>④忍气吞声，远离是非"},
  {paper_id: "13", exam_question_id: "2527", answer: "D", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ed9e55f002e.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2123", answer: "A,B,C", question_title: "关于社会主义核心价值观，党的十八大报告分别从国家、社会、个人三个层次提出了“三个倡导”。这三个倡导是指（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1953", answer: "A", question_title: "下列句子中，标点符号使用正确的一项是 &nbsp; （ &nbsp;） "},
  {paper_id: "14", exam_question_id: "2508", answer: "C", question_title: "小明参加培训的兴趣班突然宣布关闭，而其家长预付的学费尚未退费。对此，你建议小明和家长（  &nbsp; ）。\n<br>①在网络上发帖网暴兴趣班经营者\n<br>②要求经营者根据合同约定退还费用\n<br>③顺其自然，不要再参与预付费项目\n<br>④凭相关证据、凭证，提起民事诉讼"},
  {paper_id: "13", exam_question_id: "2309", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ecb2a890022.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1960", answer: "A", question_title: "子曰：“工欲( &nbsp; )其事，必先利其器”"},
  {paper_id: "15", exam_question_id: "2126", answer: "A,B,C", question_title: "党的二十大报告指出，从现在起，中国共产党的中心任务就是（ &nbsp; &nbsp;）。"},
  {paper_id: "14", exam_question_id: "2225", answer: "B,A,C", question_title: "疫情防控阻击战是一面镜子，考验着每一位公民的诚信素养。有商家坐地起价昧着良心发起“疫情财”，有人居心叵测制造散布各种谣言，更有人不知轻重地隐瞒、谎报疫情……这些行为都让人不寒而栗。我们重视诚信，是因为（ &nbsp; &nbsp;）。"},
  {paper_id: "13", exam_question_id: "2311", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ecb79760024.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1963", answer: "C", question_title: "下列哪项不是端午节的习俗? ( &nbsp; &nbsp;)"},
  {paper_id: "14", exam_question_id: "2226", answer: "C,D,A", question_title: "在道路上发生车祸后，正确的做法是（ &nbsp; &nbsp;）。"},
  {paper_id: "15", exam_question_id: "2127", answer: "A,B,C", question_title: "党的二十大报告指出，十年来，我们经历了对党和人民事业具有重大现实意义和深远历史意义的三件大事：一是（ &nbsp;），二是（ &nbsp;），三是（ &nbsp;），实现第一个百年奋斗目标。"},
  {paper_id: "13", exam_question_id: "2313", answer: "A", question_title: "有一种笔记本，原售价为每本8元，商场用如下办法促销：每次购买1~8本打九折，9~16本打八五折，17~25本打八折，超过25本打七五折，若你买15本笔记本，需付102元。 &nbsp;（ &nbsp; &nbsp;）"},
  {paper_id: "12", exam_question_id: "1964", answer: "B", question_title: "<p style=\"text-align: justify;\">“弱冠”指的是男子多少岁? ( &nbsp; &nbsp;)"},
  {paper_id: "15", exam_question_id: "2129", answer: "A,C,D", question_title: "党的二十大报告指出，我们要坚持（ &nbsp; &nbsp;），加快建设教育强国、科技强国、人才强国，坚持为党育人、为国育才，全面提高人才自主培养质量，着力造就拔尖创新人才，聚天下英才而用之。"},
  {paper_id: "13", exam_question_id: "2314", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec939e60018.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1970", answer: "B", question_title: "在古代人们尊称对方的妻子：( &nbsp; &nbsp;)"},
  {paper_id: "15", exam_question_id: "2141", answer: "A,B,C", question_title: "新中国确立的三大政治制度是（ &nbsp; &nbsp;）。"},
  {paper_id: "13", exam_question_id: "2315", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec961e30019.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1975", answer: "B", question_title: "选出没有错别字的一项（ &nbsp; &nbsp;） "},
  {paper_id: "15", exam_question_id: "2477", answer: "AC", question_title: "为了保证地方官员尽职尽责，古代中国的中央政府主要采取两条措施（  &nbsp;  ）。"},
  {paper_id: "13", exam_question_id: "2316", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec983a0001a.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1995", answer: "A", question_title: "《橘子》的作者是芥川龙之介，是（ &nbsp; ）国家的作家。"},
  {paper_id: "14", exam_question_id: "2242", answer: "A,,C,DB", question_title: "劳动者可享受的社会保险是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "2002", answer: "A", question_title: "<p style=\"text-align: justify;\">“大珠小珠落玉盘”所形容的是什么乐器的弹奏声？（ &nbsp; &nbsp;）"},
  {paper_id: "13", exam_question_id: "2317", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec9b00d001b.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2509", answer: "CD", question_title: "杭州亚运会期间，3.76万名赛会志愿者“小青荷”，148万名亚运城市志愿者“小莲子”，用热情的微笑欢迎运动健儿，用真诚的服务保障赛会运行，把爱播撒到杭州这座亚运之城。表明这些志愿者（ &nbsp;  ）。"},
  {paper_id: "15", exam_question_id: "2482", answer: "ABC", question_title: "我国农村土地流转必须遵循的重大原则是（   &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2485", answer: "ABC", question_title: "一名卖瓜农妇审被城管人员追赶，并被掀翻卖瓜的三轮车，你认为下列维权方式正确是（  &nbsp;  ）。"},
  {paper_id: "13", exam_question_id: "2323", answer: "B", question_title: "“嫦娥奔月，举国欢庆”，据计算，运载“神六”长征二号火箭在点火的第一秒通过的路程为2km，以后每秒钟通过的路程都增加2km，在达到离地面240km的高度时，火箭与飞船分离，则这个过程需要的时间是120秒.（ &nbsp; &nbsp;）"},
  {paper_id: "14", exam_question_id: "2519", answer: "ABC", question_title: "下列关于宪法表述正确的是（  &nbsp;  ）。"},
  {paper_id: "12", exam_question_id: "2326", answer: "B", question_title: "小说的几要素是（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2044", answer: "A", question_title: "生活方式的变化推动着人们消费观念的更新，也带来不同消费观念之间的碰撞。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2355", answer: "B", question_title: "《送杜少府之任蜀州》鉴赏不正确的一项是（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2523", answer: "AD", question_title: "2022年4月21日，最高人民检察院发布10件打击治理电信网络诈骗及关联犯罪典型案例。面对猖獗的网络诈骗，必须坚持惩防治结合，筑起防范诈骗“防火墙”。为了防止网络诈骗，我们应该（ &nbsp;   ）。"},
  {paper_id: "15", exam_question_id: "2056", answer: "A", question_title: "稳步提高粮食最低收购价是完善农业支持保护制度的政策措施。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2360", answer: "C", question_title: "下列词语中没有错别字的是（&nbsp;&nbsp;）"},
  {paper_id: "14", exam_question_id: "2147", answer: "B", question_title: "爱岗与敬业是相互联系在一起的。敬业是爱岗的基础，爱岗是敬业的具体表现。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2059", answer: "A", question_title: "国体与政体的关系是政体决定国体，国体反映政体。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2370", answer: "D", question_title: "下列成语正确的一项是  （&nbsp; &nbsp;）"},
  {paper_id: "15", exam_question_id: "2063", answer: "B", question_title: "监督权是公民的政治权利，公民可以采取任何方式行使监督权。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2015", answer: "B", question_title: "《面朝大海，春暖花开》诗人用抒情的笔法，将人世间对情爱和幸福的渴求锤炼成朴素的诗句，在质朴和从容的吟唱中洋溢着超越自我的生命关怀。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2073", answer: "A", question_title: "皇权专制成为中国在近代落后于世界的重要根源。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2161", answer: "A", question_title: "凡是不履行法律规定的义务或做出法律所禁止的行为都是违法行为。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2020", answer: "B", question_title: "《蒹葭》是《诗经》的第一首，是我国爱情诗歌的“开山之作”。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2077", answer: "A", question_title: "萨拉热窝事件是第一次世界大战的导火索。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2024", answer: "A", question_title: "“假如生活欺骗了你”在此并非单指上当受骗，而是指人生遭受挫折。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2080", answer: "A", question_title: "造纸术、火药、地动仪、指南针被称为我国古代四大发明。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2163", answer: "B", question_title: "管制属于刑罚种类中的附加刑。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2026", answer: "A", question_title: "我国第一位伟大的爱国主义诗人是屈原，他的代表作《离骚》。（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2171", answer: "A", question_title: "对不合格商品，消费者要求退货的，经营者应该无条件予以退货。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2033", answer: "A", question_title: "孔子首创了平民教育。（ ）"},
  {paper_id: "15", exam_question_id: "2331", answer: "A", question_title: "2001年，中国正式加入世界贸易组织。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2174", answer: "B", question_title: "劳动者解除劳动合同，应当提前3日以书面形式通知用人单位。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2175", answer: "B", question_title: "一般情况下，劳动者跳槽须支付违约金。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2332", answer: "B", question_title: "工业生产日出而作日落而息，许多时候要“靠天吃饭”。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2042", answer: "A", question_title: "<p style=\"text-align: justify;\">因为合同有一定的法律效率，所以当合同涉及劳动报酬之类的重要数字时，一定要用大写汉字。（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2408", answer: "A", question_title: "“蒹葭苍苍，白露为霜”属于景物描写，既点明了地点和景物，又点明了时节，渲染了一种苍凉幽渺的氛围和色调。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2341", answer: "B", question_title: "租赁消费是我们平时最常用的交易方式。（）"},
  {paper_id: "14", exam_question_id: "2180", answer: "B", question_title: "人民法院可直接受理没有经过仲裁程序的劳动争议案件。（ ）"},
  {paper_id: "12", exam_question_id: "2411", answer: "B", question_title: "《蒹葭》是一首叙事诗。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2439", answer: "B", question_title: "依法被剥夺政治权利的人仍然享有选举权和被选举权。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2449", answer: "A", question_title: "一个人的社会公德水平的高低是衡量其道德修养的基本尺度。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2460", answer: "B", question_title: "收到公检法机关要求汇款到“安全账户”的电话，要积极配合。（&nbsp;）"},
  {paper_id: "13", exam_question_id: "2249", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ed2b0f7002a.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1915", answer: "A", question_title: "下列句子中没有语病的一项是（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2186", answer: "A", question_title: "社会公德是公民在社会交往和社会公共生活中应该遵守的道德准则。下列选项中，属于社会公德主要内容之一的是（ &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2092", answer: "A", question_title: "宁波市生活垃圾分为四类，即厨余垃圾（餐厨垃圾）、可回收物、有害垃圾，其他垃圾，其对应的垃圾桶分别是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2188", answer: "A", question_title: "要亲近社会、融入社会，我们必须遵守社会公德。社会公德的主要内容是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1919", answer: "A", question_title: "“月上柳梢头，人约黄昏后”描写的是哪个传统节日? ( &nbsp;)"},
  {paper_id: "15", exam_question_id: "2107", answer: "C", question_title: "“洋装虽然穿在身，我心依然是中国心，我的祖先早已把我的一切烙上中国印”， 张明敏的《我的中国心》，唱出了海外游子对祖国割舍不断的感情。上述歌词表明（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2191", answer: "A", question_title: "法定继承的第一顺序继承人是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1923", answer: "D", question_title: "下面哪句话出自《孟子》? ( &nbsp; )"},
  {paper_id: "15", exam_question_id: "2109", answer: "D", question_title: "宁波市是国家历史文化名城，古称为“鄞”，（ &nbsp; ）时属会稽郡的鄞、鄮、句章三县，唐时称“明州”。"},
  {paper_id: "12", exam_question_id: "1928", answer: "C", question_title: "“桃花仙人种桃树，又摘桃花换酒钱”“桃花仙人”指的是（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2114", answer: "D", question_title: "虎门销烟的英雄是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2257", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ede3a380047.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2115", answer: "B", question_title: "（ &nbsp; ）事件标志着抗日战争的全面爆发。"},
  {paper_id: "14", exam_question_id: "2205", answer: "B", question_title: "我国的宪法和其他法律的制定者是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1939", answer: "C", question_title: "下面是某学生向老师祝寿时发言的一个片段，其中有几处不得体。修改意见不正确的一项是（ &nbsp;）<br><p style=\"text-indent: 24pt; text-align: justify;\">这次我们专程从全国各地光临母校，给我们至今健在的恩师李老师做寿，李老师视名利淡如水，看事业重如山。李老师虽已八十高龄，但依然精神矍铄，我们几个高足都感到十分欣慰......"},
  {paper_id: "13", exam_question_id: "2268", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee198a10067.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1942", answer: "B", question_title: "下列四个选项能在语义上与“天边偶尔漂浮着淡淡的白云”构成最贴切的比喻句的是：( &nbsp; )"},
  {paper_id: "14", exam_question_id: "2214", answer: "B", question_title: "社会主义职业道德的核心是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1945", answer: "A", question_title: "填入下面空缺处，与上下文衔接最恰当的一项是（ &nbsp;） 学习知识要一点一滴，善于积累: ____________ ；平凡的努力虽不惊人，却能攀登万仞高峰。"},
  {paper_id: "15", exam_question_id: "2122", answer: "D", question_title: "《联合国宪章》规定了联合国的宗旨。该宗旨可以概括为（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2219", answer: "A", question_title: "在江西南昌，从19位农民工兄弟合力抬车救人，到12岁小女孩夏娟面对火灾敲门叫醒邻居，再到朱贤度和五名学生的见义勇为行为，这一件件真实感人的事迹，让每一个人都真切地感受到（ &nbsp; ）的力量在英雄城传递。"},
  {paper_id: "12", exam_question_id: "1949", answer: "D", question_title: "下列加了【】括号的成语使用不妥当的一项是（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2378", answer: "B", question_title: "辛亥革命后，中国社会生活发生了巨大变化。假如你是一位已经接受新生事物并生活在当时的上海某政府官员，你不可能（&nbsp;）。"},
  {paper_id: "12", exam_question_id: "1957", answer: "C", question_title: "“忽如一夜春风来，千树万树梨花开”写的是 ( &nbsp; )。"},
  {paper_id: "13", exam_question_id: "2284", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee907fb00aa.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2381", answer: "A", question_title: "中国是一个饮食文化发达的国家，其中以粤菜、川菜、淮扬菜和（ &nbsp;  ）菜统称我国四大菜系。"},
  {paper_id: "13", exam_question_id: "2293", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee9853400ad.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2431", answer: "D", question_title: "当前我国解决大规模人口流动问题，最安全、最快捷、最经济、最环保、最可靠的交通方式是（  &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1972", answer: "B", question_title: "对《乡愁》全诗的理解，错误的一项是（ &nbsp; &nbsp; ）"},
  {paper_id: "13", exam_question_id: "2295", answer: "B", question_title: "<p>一个长6cm，宽4cm，高8cm的长方体盒子，最多能放（ &nbsp; ）个棱长为2cm的正方体木块？</p>"},
  {paper_id: "14", exam_question_id: "2476", answer: "B", question_title: "李虎在校因琐事把同学王刚打成重伤，被公安机关刑事拘留。其父母为下岗职工，经济十分困难。王律师听说此事后，主动提出给李虎担任辩护人，提供法律援助。王律师提供的法律援助的形式是（  &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2433", answer: "A", question_title: "根据国际标准，当一个国家或地区60岁以上老年人口占人数总数的（ &nbsp;  ），或65岁以上老年人口占总数的（ &nbsp;  ），即意味着这个国家或地区处于老龄化社会。"},
  {paper_id: "12", exam_question_id: "1985", answer: "C", question_title: "下列选项中与“亡羊补牢”意思最接近的是：( &nbsp; &nbsp;)"},
  {paper_id: "13", exam_question_id: "2297", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eeb376b00bc.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2450", answer: "D", question_title: "2024年3月12日，国务院政府工作报告正式发布，明确新一年的首要任务为大力推进现代化产业体系建设，加快发展（  &nbsp;  ）"},
  {paper_id: "14", exam_question_id: "2506", answer: "A", question_title: "蒋某因家庭矛盾，将手机、平板电脑、水果刀等物品从14楼扔出窗外，砸落在小区楼下停放的三辆轿车上。当地法院以高空抛物罪判处蒋某有期徒刑6个月，并处罚金3000元。针对这起案件，下列表述正确的是（ &nbsp;  ）。"},
  {paper_id: "12", exam_question_id: "1992", answer: "B", question_title: "<p style=\"text-align: justify;\">“生当作人杰，死亦为鬼雄，至今思项羽，不肯过江东。”是谁咏赞项羽的名句? ( &nbsp; &nbsp; )"},
  {paper_id: "14", exam_question_id: "2224", answer: "A,C,D", question_title: "2019年3月，浙江宁波一辆公交车在行驶途中，车上某乘客突然晕倒。危急时刻，车上乘客齐心照顾晕倒的病人，司机驾车直奔医院，使该乘客得到及时救治。对此，以下说法正确的是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1993", answer: "B", question_title: "<p style=\"text-align: justify;\">“滚滚长江东逝水，浪花淘尽英雄。……”这是我国古代文学名著（ &nbsp; &nbsp;）的开篇词。"},
  {paper_id: "15", exam_question_id: "2138", answer: "A,C,D", question_title: "组成我国基层民主自治体系的主要形式是（ &nbsp; &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2003", answer: "B", question_title: "<p style=\"text-align: justify;\">王昭君没有得到汉元帝的召见而远嫁匈奴单于，是因为（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2465", answer: "ABCD", question_title: "改革开放以来我们取得一切成绩和进步的根本原因，归结起来就是（ &nbsp;  ）"},
  {paper_id: "12", exam_question_id: "2008", answer: "B", question_title: "“初出茅庐”中的“茅庐”本意是指谁的的住处？（ &nbsp; &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2234", answer: "A,B,C", question_title: "我国产品质量法关于“三包”规定是指（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "2011", answer: "C", question_title: "中国古典章回小说常常以诗词引出人物和故事。在《水浒传》中有一首《鹧鸪天》“罡星起义在山东，杀曜纵横水浒中。可是七星成聚会，却于四海显英雄。人似虎，马如龙，黄泥冈上巧施功。满驮金贝归山寨，懊悔中书老相公。”请问它引出的是下面哪个故事（ &nbsp; &nbsp;）"},
  {paper_id: "14", exam_question_id: "2237", answer: "A", question_title: "下列属于法律援助的是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "2324", answer: "A", question_title: "《红楼梦》是（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2475", answer: "ABCD", question_title: "我们进行中国特色社会主义文化建设的重要内容是（   &nbsp;  ）。"},
  {paper_id: "14", exam_question_id: "2239", answer: "A,B,C", question_title: "人身自由是公民的基本权利之一，以下属于人身自由权的是（ &nbsp; &nbsp;）。"},
  {paper_id: "14", exam_question_id: "2515", answer: "AC", question_title: "“七一勋章”获得者陈红军，在同外军战斗中英勇作战，誓死不屈，为捍卫祖国领土主权，维护国家核心利益壮烈牺牲。陈红军烈士所履行的公民基本义务是（ &nbsp;   ）。"},
  {paper_id: "15", exam_question_id: "2481", answer: "ABD", question_title: "2024年12月11日至12日，中央经济工作会议在北京举行。会议要求，2025年要坚持（ &nbsp;  ），充实完善政策工具箱，提高宏观调控的前瞻性、针对性、有效性。"},
  {paper_id: "12", exam_question_id: "2327", answer: "A", question_title: "课文《红楼梦（节选）》中\"雨村便急忙修书二封\"中的\"急忙\"一词揭示贾雨村：（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2525", answer: "AC", question_title: "在社会生活中，我们要学会用法律与人打交道。在遇到法律问题和权益受到侵害时，要及时寻求法律救助，依靠法律维护自己的合法权益。下列观点正确的有（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2526", answer: "ABCD", question_title: "全面推进依法治国的基本要求是（ &nbsp;   ）。"},
  {paper_id: "15", exam_question_id: "2043", answer: "A", question_title: "消费水平受很多因素影响，其中主要因素是居民收入水平和物价总体水平。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2145", answer: "A", question_title: "基本道德规范是所有道德规范中起基础和核心作用的规范。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2045", answer: "A", question_title: "健康投资是是提高健康水平，改善生活质量的重要途径。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2365", answer: "D", question_title: "下列广告语中没有错别字的一项是（&nbsp;&nbsp;）"},
  {paper_id: "15", exam_question_id: "2046", answer: "B", question_title: "GDP是消费者物价指数的英文缩写，通常作为通货膨胀水平的重要指标。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2372", answer: "A", question_title: "下列成语正确的一项是（&nbsp; ）"},
  {paper_id: "14", exam_question_id: "2150", answer: "A", question_title: "家庭美德也是评价人们在婚姻、家庭、邻里之间交往中的行为是非善恶的标准。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2050", answer: "A", question_title: "实体经济是财富创造的根本源泉，国家强盛的重要支柱。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2387", answer: "D", question_title: "对修辞方法及其作用分析得不正确的一项是（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2152", answer: "A", question_title: "市场经济是充满竞争的经济，谁诚实守信，谁就会在竞争中吃亏，最后被淘汰出局。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2389", answer: "D", question_title: "下列句子中没有错别字的一句是（  ）"},
  {paper_id: "14", exam_question_id: "2157", answer: "B", question_title: "18周岁以上的公民是成年人，都具有完全民事行为能力。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2014", answer: "A", question_title: "《乡愁》是余光中的代表作，诗人把炽热深沉的思绪寄寓在鲜明的意象之中，把民族感情和诗歌艺术融于一体。（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2029", answer: "A", question_title: "余光中是20世纪90年代在大陆最有影响的台湾诗人和散文作家之一，《乡愁》是他的代表作之一。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2067", answer: "A", question_title: "任何境外组织和个人不得干预我国的宗教事务。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2031", answer: "A", question_title: "演讲的语言应该通俗易懂，符合口语的要求，要做到讲起来上口，听起来入耳。（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2169", answer: "B", question_title: "在买卖关系中，如果卖方违约的,则应当承担双倍返还订金的责任。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2069", answer: "A", question_title: "宗教信仰与封建迷信都相信和崇拜神灵或超自然力量，两者没有区别。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2035", answer: "B", question_title: "“宜将剩勇追穷寇，不可沽名学霸王”中的“霸王”是指刘邦（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2170", answer: "A", question_title: "被继承人有遗嘱的按遗嘱继承，没有遗嘱的按照法律规定继承。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2040", answer: "A", question_title: "《当你老了》是普希金于1893年为毛特·冈而作的一首爱情诗。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2072", answer: "B", question_title: "现在日本和英国的君主与中国古代的君主一样都叫“国王”。（ &nbsp; ） "},
  {paper_id: "15", exam_question_id: "2075", answer: "A", question_title: "“中华民族到了最危险的时候”这句歌词出自《义勇军进行曲》。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2401", answer: "A", question_title: "“参差荇菜，左右流之”，参差的含义是长短不齐。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2458", answer: "B", question_title: "被告人郑某多次窃取他人物品，被判处拘役四个月。该判决的依据是《中华人民共和国民法典》。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2340", answer: "B", question_title: "我国人文旅游资源丰富，其中河姆渡遗址在我国的陕西省。（）"},
  {paper_id: "14", exam_question_id: "2459", answer: "A", question_title: "食品安全违法行为都要承担刑事责任，受刑罚处罚。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2461", answer: "B", question_title: "民事责任包括警告、记过、罚款、没收违法所得、行政拘留等。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2417", answer: "A", question_title: "家乡,我日夜思念的家乡,多么想要回到母亲的怀抱是抒情表达方式。（&nbsp;）"},
  {paper_id: "13", exam_question_id: "2244", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec590c70007.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1893", answer: "D", question_title: "下列句子加括号【】的字读音，不正确的一项是（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2189", answer: "D", question_title: "某外卖骑手小杨为了赶时间送外卖，闯红灯被交警罚款100元；擦伤小王的私家车赔偿800元；私家车车主把小杨打成重伤被判拘役3个月，罚金10000元。上述三种违法行为分别是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2247", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ec6f14b000d.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2093", answer: "A", question_title: "“花明天的钱，圆今天的梦”指的消费形式是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2203", answer: "C", question_title: "对“邻里团结”理解正确的是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1902", answer: "B", question_title: "下列句子中，修辞方法使用不恰当的一项是 （ &nbsp;）"},
  {paper_id: "12", exam_question_id: "1903", answer: "A", question_title: "<p style=\"text-indent: 12pt;\">选出对下列各句运用的修辞方法依次正确判断的一项：（ &nbsp; ）<p style=\"text-indent: 12pt;\">①风带着雨星，像在寻找什么似的，东一头西一头地乱撞。<p style=\"text-indent: 12pt;\">②春天像刚落地的娃娃，从头到脚都是新的。<p style=\"text-indent: 12pt;\">③乱花渐欲迷人眼，浅草才能没马蹄。<p style=\"text-indent: 12pt;\">④狂风吹不倒它，洪水淹不没它，严寒冻不死它，干旱旱不坏它。"},
  {paper_id: "13", exam_question_id: "2259", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edf05700050.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1910", answer: "A", question_title: "下列有关文学常识的说法，不恰当的一项是（ &nbsp;）"},
  {paper_id: "13", exam_question_id: "2262", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee02732005b.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2215", answer: "A", question_title: "区分犯罪和其他违法行为的法律标志是（ &nbsp; ）。 &nbsp;"},
  {paper_id: "15", exam_question_id: "2106", answer: "D", question_title: "下列属于违背我国宗教政策的是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2217", answer: "A", question_title: "对严重妨碍社会管理秩序的犯罪行为，要依据（ &nbsp; ）来处罚。 "},
  {paper_id: "15", exam_question_id: "2112", answer: "A", question_title: "根据“一国两制”构想的内涵，其最重要的原则是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2266", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee14e4b0065.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1924", answer: "C", question_title: "<p style=\"text-align: justify;\">下列哪个不是北京的别称? ( &nbsp; )"},
  {paper_id: "13", exam_question_id: "2269", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee20bc7006c.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2222", answer: "D", question_title: "在抗击新冠肺炎疫情期间，个别网民在未经核实的情况下，在网络上发布、转发不实信息，甚至制造传播谣言，造成不良社会影响，被公安机关依法查处。这警示我们公民应（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2469", answer: "B", question_title: "犯罪的最基本特征是（&nbsp;）。"},
  {paper_id: "15", exam_question_id: "2374", answer: "B", question_title: "20世纪最伟大的物理学家是（&nbsp;）。"},
  {paper_id: "14", exam_question_id: "2492", answer: "A", question_title: "从业人员对待职业服务对象的态度不能有亲疏、贵贱之分，不管是领导还是群众、是熟人还是生人、是强者还是弱者，都应自觉遵守规章制度，一视同仁、周到服务。这是职业道德建设中（ &nbsp;  ）。"},
  {paper_id: "15", exam_question_id: "2424", answer: "A", question_title: "1958年（  &nbsp; ）开播，标志着中国电视事业的诞生。"},
  {paper_id: "14", exam_question_id: "2503", answer: "D", question_title: "市民罗某因遛狗未拴狗绳，导致恶犬咬伤路人。该地派出所依法对其给予罚款一万元，并没收恶犬的处罚。处罚罗某是因为其做出了（ &nbsp;  ）的行为而要承担（ &nbsp;  ）。"},
  {paper_id: "15", exam_question_id: "2434", answer: "C", question_title: "第二次世界大战后最大的一场局部战争是（ &nbsp;  ）"},
  {paper_id: "13", exam_question_id: "2305", answer: "A", question_title: "<p>某城市为保护环境，维护水资源，鼓励市民家庭节约用水，作出了如下规定：每月用水不超过4吨，按每吨2元收费，每月超过4吨，超过部分加倍收费，某市民家庭某月缴费20元，该市民家庭这个月实际用水为（ &nbsp; &nbsp;）</p>"},
  {paper_id: "12", exam_question_id: "1984", answer: "A", question_title: "下列有关文学常识的表述，没有错误的一项是（ &nbsp; &nbsp;）"},
  {paper_id: "12", exam_question_id: "1989", answer: "A", question_title: "神话故事“夸父逐日”出自哪部书? ( &nbsp; &nbsp;)"},
  {paper_id: "14", exam_question_id: "2228", answer: "A,B,D", question_title: "下列行为属于行政违法行为的是（ &nbsp; &nbsp;）。"},
  {paper_id: "14", exam_question_id: "2235", answer: "A", question_title: "对驾驶机动车在遵守《道路交通安全法》方面理解正确的是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1996", answer: "C", question_title: "下面哪个剧种被称为“中国百戏之师”? ( &nbsp; &nbsp; )"},
  {paper_id: "15", exam_question_id: "2130", answer: "A,C,B", question_title: "按照消费目的的不同，生活消费可以分为（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1997", answer: "A", question_title: "中国书法所谓的“颜筋柳骨”的“颜”是指（ &nbsp; &nbsp;）"},
  {paper_id: "14", exam_question_id: "2236", answer: "A,B,C", question_title: "下列情形中，劳动者应当认定为工伤的是（ &nbsp; &nbsp;）。"},
  {paper_id: "15", exam_question_id: "2135", answer: "D,B", question_title: "农业的地位和作用可以用一句话来概括：国民经济的基础，如何理解这句话？（ &nbsp; &nbsp;） "},
  {paper_id: "12", exam_question_id: "1999", answer: "C", question_title: "诗句“宜将剩勇追穷寇，不可沽名学霸王”中的“霸王”是指（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2136", answer: "A,B,C,D", question_title: "农民实现致富的途径，是多种形式、多渠道、综合型的。下列表述中关于可以实现致富的正确选项有（ &nbsp; &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2012", answer: "C", question_title: "<p style=\"text-align: justify;\">天下亭台楼阁，因诗文而闻名的很多，下列诗文与所描写的亭台楼阁---黄鹤楼、岳阳楼、醉翁亭、滕王阁，对应顺序正确的一项是（ &nbsp; ）<p style=\"text-align: justify;\">（1）先天下之忧而忧，后天下之乐而乐。<p style=\"text-align: justify;\">（2）醉翁之意不在酒，在乎山水之间也。<p style=\"text-align: justify;\">（3）落霞与古鹜齐飞，秋水共长天一色。<p style=\"text-align: justify;\">（4）日暮乡关何处是？烟波江上使人愁。"},
  {paper_id: "12", exam_question_id: "2334", answer: "A", question_title: "课文《红楼梦（节选）》中\"远远的充发了才罢\"，句中\"远远\"一词说明（&nbsp; ）"},
  {paper_id: "14", exam_question_id: "2518", answer: "ABC", question_title: "下列符合《道路交通安全法》对机动车有关规定的是（   &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2352", answer: "C", question_title: "下面是对课文《红楼梦（节选）》中门子献计时性格的概括，正确的一组是（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2064", answer: "B", question_title: "公民可以通过社情民意反映制度行使监督权。 （ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2065", answer: "A", question_title: "信仰是人们的重要精神支柱，凡是精神正常的成年人，总会有一定的信仰。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2013", answer: "A", question_title: "<p>《再别康桥》是现代诗人徐志摩写的。（ &nbsp;）</p>"},
  {paper_id: "15", exam_question_id: "2068", answer: "A", question_title: "文化对人的影响是全方位的，人创造了文化，文化又造就了人。（ &nbsp; ） "},
  {paper_id: "12", exam_question_id: "2023", answer: "A", question_title: "“横眉冷对千夫指，俯首甘为孺子牛。”运用了对偶的修辞手法。（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2446", answer: "A", question_title: "犯罪是指违法情节严重对社会危害很大，触犯刑法并依法受刑罚的行为。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2025", answer: "B", question_title: "四书五经”中,“四书”是指《大学》《中庸》《春秋》《孟子》。（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2447", answer: "A", question_title: "用人单位为保证本单位的安全，可以向求职者收取押金或扣押居民身份证。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2041", answer: "A", question_title: "民间故事是民间文学的一种，由民间创作并传播。它具有虚构的成分，既充满幻想，又表现出民间的生活和智慧。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2082", answer: "A", question_title: "1964年10月，中国成功爆炸了第一颗原子弹。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2453", answer: "A", question_title: "法律援助是一种无偿的法律服务。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2396", answer: "A", question_title: "《假如生活欺骗了你》诗人告诫我们：无论我们生活遇到什么损失和挫折，都不要失去战斗的决心，要相信一切都是短暂的，光明必将驱走黑暗，正义必将战胜邪恶。（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2456", answer: "A", question_title: "法律通过规定公民的权利和义务，为每个人提供了自由生存和发展的空间。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2335", answer: "B", question_title: "浙江省属于亚热带季风气候，阳光充足，雨热同期，最适宜棉花生长。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2400", answer: "A", question_title: "《水调歌头》“此事古难全”里的“此事”指：人有悲欢离合，月有阴晴圆缺。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2464", answer: "A", question_title: "现实生活中，我们要力求做到自觉守法、遇事找法、解决问题靠法。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2466", answer: "A", question_title: "犯罪的法律后果是刑罚，犯罪人将被限制或剥夺权益甚至生命。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2418", answer: "B", question_title: "对书的考察,最可靠的评判官是你的心灵——非同寻常的对知识的敏感,超乎群伦的观人察事的眼光以及对人文精神的深刻把握采用的是叙述的表达方式。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2088", answer: "D", question_title: "新冠疫情发生以来，在以习近平同志为核心的党中央坚强领导下，始终把人民群众生命安全和身体健康放在第一位，全面提高依法防控、依法治理能力，为疫情防控工作提供有力法治保障。上述体现的发展思想和治理国家的基本方略分别是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1898", answer: "B", question_title: "依次填入下列各句横线处的词语，最恰当的一组是 （ &nbsp; &nbsp; ） （1）阿Q这个人物也是有生活____的，更重要的是他反映了那个时代国民精神的一些弊病。（2）屈原披头散发，形容枯槁，神情悲怆，他 ____于汨罗江畔放不下故国热土和自己永远挚爱的人民。（3）列夫·托尔斯泰说过，爱的嫩芽是细弱的，____长起来的时候，它 ____强大无比，所以必须精心呵护。<br>"},
  {paper_id: "12", exam_question_id: "1921", answer: "A", question_title: "下列哪个成语典故与项羽有关? ( &nbsp;)"},
  {paper_id: "14", exam_question_id: "2213", answer: "A", question_title: "我国婚姻法规定，结婚必须符合的法定年龄条件是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1932", answer: "A", question_title: "<p style=\"text-align: left;\">对《再别康桥》这首诗的理解有误的一项是（ &nbsp; &nbsp;）"},
  {paper_id: "15", exam_question_id: "2103", answer: "A", question_title: "宁波市法制办通过宁波日报向社会公开征求对《宁波市生活垃圾分类管理条例（草案）》的意见，广大市民踊跃参与，提出建议。这是公民通过（ &nbsp; ）参与民主决策。"},
  {paper_id: "13", exam_question_id: "2270", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee27fe00071.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1933", answer: "A", question_title: "<p style=\"text-align: left;\">下列各组中的加【】括号的词，读音全相同的一项是（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2479", answer: "C", question_title: "刘某委托周律师担任自己刑事附带民事诉讼的代理人。在当事人与律师的委托关系中，刘某应有的权利有（ &nbsp;  ）。"},
  {paper_id: "14", exam_question_id: "2487", answer: "D", question_title: "劳动者依法享有的社会保险五大险种中，个人不用缴费的是（ &nbsp;  ）。"},
  {paper_id: "14", exam_question_id: "2491", answer: "A", question_title: "不同时代具有不同的时代精神。当今时代，我们大力弘扬的时代精神的核心是（  &nbsp; ）。 "},
  {paper_id: "13", exam_question_id: "2276", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edbefcd0039.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2493", answer: "B", question_title: "为创建全国文明典范城市，宁波市广大市民纷纷主动参与，形成了人人参与创建，人人支持创建的良好局面。市民的行为是在（ &nbsp;  ）。"},
  {paper_id: "12", exam_question_id: "1948", answer: "C", question_title: "下列文学常识表述不正确的一项（ &nbsp; &nbsp;）"},
  {paper_id: "12", exam_question_id: "1952", answer: "B", question_title: "下列各句中，没有语病的一句是( &nbsp;)"},
  {paper_id: "15", exam_question_id: "2445", answer: "A", question_title: "下列属于影响人口迁移到经济因素的是（  &nbsp; ）"},
  {paper_id: "13", exam_question_id: "2298", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eeb62df00bd.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1966", answer: "B", question_title: "河姆渡遗址位于：( &nbsp; )"},
  {paper_id: "15", exam_question_id: "2452", answer: "A", question_title: "中央经济工作会议2024年12月11日至12日在北京举行。会议为中国经济高质量发展把舵定向。会议将（   &nbsp; ）摆在2025年九项重点任务之首。"},
  {paper_id: "13", exam_question_id: "2303", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eed692800cb.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1971", answer: "B", question_title: "水浒一百单八将中有几位女性? ( &nbsp; &nbsp;)"},
  {paper_id: "12", exam_question_id: "1979", answer: "A", question_title: "选出与“写鬼写妖高人一等”格式一致的一项（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2132", answer: "C,D", question_title: "下列有关消费者维护合法权益的正确途径是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1981", answer: "A", question_title: "<p style=\"text-align: left;\">下面四副对联评说的对象依次是（ &nbsp; ） <p style=\"text-indent: 18pt; text-align: left;\">①一门三父子，都是大文豪；诗赋传千古，峨眉共比高。<p style=\"text-indent: 18pt; text-align: left;\">②世上疮痍诗中圣哲，民间疾苦笔底波澜。<p style=\"text-indent: 18pt; text-align: left;\">③写鬼写妖高人一筹，刺贪刺虐入骨三分。<p style=\"text-indent: 18pt; text-align: left;\">④盛唐诗酒无双士，青莲文苑第一家。"},
  {paper_id: "12", exam_question_id: "1990", answer: "A", question_title: "孔子弟子中擅长做生意的是谁? ( &nbsp; &nbsp;)"},
  {paper_id: "15", exam_question_id: "2137", answer: "A,B,C,D", question_title: "我国农业面临的问题是（ &nbsp; &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1991", answer: "A", question_title: "<p style=\"text-align: justify;\">“红娘”今指代为爱情牵线搭桥的人，请问她最早出现在哪部文学作品中? ( &nbsp; &nbsp;)"},
  {paper_id: "12", exam_question_id: "1994", answer: "B", question_title: "《水浒传》中“醉打蒋门神”的人是（ &nbsp; &nbsp;）。"},
  {paper_id: "14", exam_question_id: "2524", answer: "AC", question_title: "有识之士认为：机动车“礼让斑马线”行动要从“礼让”向“理让”转变，不仅要规范机动车避让行人，更要倡导行人与机动车互相避让，违法行走的路人，不应在“礼让斑马线”的范围。这一观点强调了公民（  &nbsp;  ）。"},
  {paper_id: "15", exam_question_id: "2486", answer: "CD", question_title: "科技进步推动社会生产力的发展，对人类社会产生广泛而深远的影响。下列有关科技成就的叙述，正确的是（  &nbsp;  ）。"},
  {paper_id: "13", exam_question_id: "2319", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eca0212001d.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2052", answer: "A", question_title: "就业是民生之本，解决就业问题，最根本的一条，还是要靠发展经济。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2333", answer: "A", question_title: "课文《红楼梦（节选）》中\"冯家得了许多烧埋银子，也就无甚话说了\"，说明：（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2070", answer: "A", question_title: "在当代中国，先进文化的指导思想是马克思主义。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2363", answer: "A", question_title: "下列词语中没有错别字的是 （  ）"},
  {paper_id: "14", exam_question_id: "2173", answer: "B", question_title: "无固定期限劳动合同是用人单位与劳动者约定无起始时间的劳动合同。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2078", answer: "A", question_title: "第二次世界大战是迄今为止规模最大、破坏最大的全球性战争。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2329", answer: "A", question_title: "辛亥革命对社交礼仪的革新意义重大，显示出平等、自由的文明精神。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2028", answer: "A", question_title: "莎士比亚的“四大悲剧”是《哈姆雷特》、《奥瑟罗》、《李尔王》和《麦克白》。（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2402", answer: "A", question_title: "《诗经》分为“风”、“雅”、“颂”三部分，其中“风”又称“国风”，是各地的民间歌谣。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2330", answer: "B", question_title: "唐朝时郑成功两次下西洋，增强了中国与世界的联系。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2336", answer: "A", question_title: "台风是浙江省最主要的农业气象灾害，其严重程度居气象灾害之首。（）"},
  {paper_id: "12", exam_question_id: "1904", answer: "A", question_title: "与“那航船，就像一条大白鱼背着一群孩子在浪花里蹿”一句所用修辞方法不相同的一项是 （ &nbsp; &nbsp;）"},
  {paper_id: "12", exam_question_id: "2415", answer: "A", question_title: "我有一双大大的眼睛,一头黑黑的头发,一个小小的嘴采用的是描写手法。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "1906", answer: "A", question_title: "为下文空缺处选择合适内容填充，最佳的句子是：（ &nbsp;） &nbsp;围绕在海港周围山坡上的那一片灯光，从半空倒映在乌蓝的海面上，随着波浪晃动着，闪烁着，__________，和那一片片密布在苍穹里的星斗互相辉映，煞是精彩。"},
  {paper_id: "13", exam_question_id: "2251", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0eeef69a00d1.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "2416", answer: "A", question_title: "这种芳香油容易挥发,扩散到空气中的芳香油分子,刺激人的嗅觉器官产生芳香的感觉,这就是花香采用的说明的表达方式。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "1911", answer: "B", question_title: "下列加点的固定短语使用恰当的一项是（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2421", answer: "A", question_title: "石拱桥的桥洞成弧形，就像虹。运用了打比方的说明方法。（&nbsp;）"},
  {paper_id: "13", exam_question_id: "2263", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee04bb9005c.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1926", answer: "B", question_title: "<p style=\"text-align: justify;\">文人对各种植物有自己的偏爱，陶渊明喜爱菊花，北宋文豪苏东坡则说过：宁可食无肉，不可：( &nbsp; )"},
  {paper_id: "15", exam_question_id: "2083", answer: "D", question_title: "当前我国社会主要矛盾已经转化为人民日益增长的（ &nbsp; ）和（ &nbsp; ）之间的矛盾。"},
  {paper_id: "12", exam_question_id: "1935", answer: "A", question_title: "下列句子中没有错别字的一项是（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2086", answer: "A", question_title: "党的十九届六中全会指出，党确立习近平同志（ &nbsp; ），确立（ &nbsp; ）的指导地位，反映了全党全军全国各族人民共同心愿，对新时代党和国家事业发展、对推进中华民族伟大复兴历史进程具有决定性意义。"},
  {paper_id: "13", exam_question_id: "2278", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee42a980082.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2095", answer: "D", question_title: "俗话说“天有不测风云人有旦夕祸福”为了减少风险，防范后患，保障生活，你认为最有效的投资方式是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2281", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee5fd210095.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2196", answer: "B", question_title: "解决劳动争议的正确程序是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1961", answer: "C", question_title: "“君子食无求饱，居无求安，敏于事而( &nbsp; )”。"},
  {paper_id: "12", exam_question_id: "1965", answer: "B", question_title: "<p style=\"text-align: justify;\">“入木三分”这个成语原本是用来形容什么的? ( &nbsp; &nbsp;)"},
  {paper_id: "14", exam_question_id: "2206", answer: "B", question_title: "犯罪与一般违法行为区别的最本质特征是（ &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2116", answer: "B", question_title: "下列重大历史事件，按发生时间的先后顺序排列正确的选项是（ &nbsp; ）。<br>①开国大典 &nbsp; ②抗战胜利 &nbsp; &nbsp;③五四运动 &nbsp; &nbsp;④中共诞生 "},
  {paper_id: "12", exam_question_id: "1976", answer: "A", question_title: "<p style=\"text-align: left;\">下面是一封求职信的主要内容，其中有几处用词不当。修改意见不正确的一项是（ &nbsp; ）<br>日前惠顾你公司网站，得知招聘经理助理的消息，我决定应聘。我是科技大学经济管理专业的应届毕业生，学习成绩优秀，身体健康，表达能力强。现寄上我的相关资料，如有意向，可尽快与我洽谈。"},
  {paper_id: "12", exam_question_id: "1978", answer: "D", question_title: "<p style=\"text-align: justify;\">对下面四句话所用修辞方法的判断，正确的是：（ &nbsp; &nbsp;） &nbsp; <p style=\"text-align: justify;\">①那又浓又翠的景色，简直是一幅青绿山水画。 <p style=\"text-align: justify;\">②白发三千丈，缘愁似个长。<p style=\"text-align: justify;\">③远寺的钟声突然惊醒了海的酣梦，它恼怒似的激起波浪的兴奋。"},
  {paper_id: "15", exam_question_id: "2121", answer: "A", question_title: "当今世界两大主题是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2001", answer: "B", question_title: "《论语》中的“见贤思齐焉，见不贤而内自省也”应做如何翻译？（ &nbsp; &nbsp;）"},
  {paper_id: "12", exam_question_id: "2004", answer: "B", question_title: "屈原是春秋时代哪国人？（ &nbsp; &nbsp;）"},
  {paper_id: "12", exam_question_id: "2005", answer: "C", question_title: "神话《白蛇传》中“白娘娘盗仙草”盗的是（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2131", answer: "A,B,C,D", question_title: "树立正确的消费观，应践行以下哪些原则（ &nbsp; &nbsp;）。"},
  {paper_id: "15", exam_question_id: "2473", answer: "ABD", question_title: "关于文化的重要性，下列说法正确的是（  &nbsp;   ）。"},
  {paper_id: "14", exam_question_id: "2517", answer: "A", question_title: "劳动合同试用期说法正确的是（  &nbsp;  ）。"},
  {paper_id: "12", exam_question_id: "2392", answer: "A", question_title: "下列句子运用的说明方法错的一项（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2017", answer: "A", question_title: "“一千个读者有一千个哈姆雷特”中的哈姆雷特是英国剧作家莎士比亚作品中的人物。（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2048", answer: "B", question_title: "当前火爆的带货直播为消费者提供新的消费方式，对消费者来讲只有好处。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2018", answer: "A", question_title: "“满纸荒唐言,一把辛酸泪！都云作者痴，谁解其中味？”这是曹雪芹对《红楼梦》读者的一种期待。（ ）"},
  {paper_id: "14", exam_question_id: "2149", answer: "A", question_title: "职业道德是从业者的立身之本。 （ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2049", answer: "B", question_title: "当前年轻人结婚时大操大办的现象违背了“保护环境、绿色消费”的消费原则。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2062", answer: "A", question_title: "企业工会的工作原则是促进企业发展，维护企业主权益。( &nbsp; &nbsp;)"},
  {paper_id: "14", exam_question_id: "2159", answer: "B", question_title: "法律规定视听资料不能算作证据。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2394", answer: "B", question_title: "《红楼梦》中贾雨村胡乱判案后就寻了个不是把葫芦庙内沙弥新门子远远充发了。唯一的原因是新门子了解他往日贫贱的底细。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2160", answer: "A", question_title: "我国公民的基本权利和义务具有广泛性、真实性、平等性、一致性。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2437", answer: "A", question_title: "道德是社会关系的基石，是人际和谐的基础。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2343", answer: "A", question_title: "尊重文化多样性，首先要尊重自己民族的文化。（）"},
  {paper_id: "12", exam_question_id: "1896", answer: "A", question_title: "依次填入下列横线处的词语，最恰当的一项是（ ）<br>①________三年的苦心研究，他终于在新品种的开发方面取得了突破性进展。 &nbsp;②由于缺乏诚意，双方都不肯作出让步，争端问题________未能得到解决。 &nbsp;③米洛斯的维纳斯是一件________伟大的作品，至今仍震撼着不同肤色的欣赏者的心灵。"},
  {paper_id: "15", exam_question_id: "2091", answer: "C", question_title: "2005年10月26日，宁波被命名为首批“全国文明城市”。2020年，高分蝉联全国文明城市“（ &nbsp; ）连冠”。如今，宁波在全国率先提出争创全国文明（ &nbsp; ）城市的目标。"},
  {paper_id: "15", exam_question_id: "2108", answer: "A", question_title: "对待文化的多样性，正确态度应该是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2208", answer: "A", question_title: "中华人民共和国的一切权力属于（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1907", answer: "D", question_title: "填入下面空缺处，与上下文衔接最恰当的一项是（ &nbsp; ）这就好比一个人远远而来，最初我们只看到______，然后又看清了______ ，然后又看清了 ______，最后才看清了______。 ①他是肥是瘦 &nbsp; &nbsp;②他穿的是长衣或短褂 &nbsp; &nbsp;③他是方脸或圆脸 &nbsp; &nbsp;④他的眉目乃至音容笑貌 "},
  {paper_id: "15", exam_question_id: "2376", answer: "A", question_title: "“两弹元勋”、“杂交水稻之父”、“现代科学之父”分别对应的是（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2483", answer: "A", question_title: "确立劳动关系，应同时订立书面合同。未同时订立的，应当自用工之日起（  &nbsp; ）内订立。"},
  {paper_id: "12", exam_question_id: "1941", answer: "B", question_title: "下面句子没有使用修辞的一项是：（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2425", answer: "A", question_title: "设施大棚葡萄可提早成熟，甲鱼只养了2年就能上市，这是因为人们改造了（ &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1951", answer: "C", question_title: "选出下面句子没有语病的一项（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2440", answer: "D", question_title: "“枣开花，种棉花”反映了农业生产的特点是具有（ &nbsp;   ）"},
  {paper_id: "14", exam_question_id: "2500", answer: "A", question_title: "一位满身泥浆的工人怕弄脏公交车的座位，疲惫地坐到公交车的过道上。司机对他说：“师傅，请坐到座位上吧。”他们身上体现出的品质是（  &nbsp; ）"},
  {paper_id: "13", exam_question_id: "2304", answer: "D", question_title: "<p>某运动用品店开业大酬宾，全部商品九折销售，小明想购买两个标价为100元的篮球，他需要支付的金额为（ &nbsp; &nbsp;）</p>"},
  {paper_id: "14", exam_question_id: "2501", answer: "C", question_title: "“一次不公正的审判比数次违法危害更烈，因为违法不过是弄脏了水流，而不公正的审判则是败坏了水源。”说明是（  &nbsp; ）依法治国的生命线。"},
  {paper_id: "12", exam_question_id: "1982", answer: "C", question_title: "下列诗句，不能体现诗人博大胸怀的诗句的一项是（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2223", answer: "A,B", question_title: "家庭美德，是指人们在家庭生活中调整家庭成员间关系、处理家庭问题时所遵循的高尚的道德规范。据此判定，下列符合要求的有（ &nbsp; &nbsp;）。"},
  {paper_id: "13", exam_question_id: "2307", answer: "B", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ecad1b10020.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1998", answer: "D", question_title: "揭示了“偶然与必然”关系的寓言故事是（ &nbsp; &nbsp;）"},
  {paper_id: "14", exam_question_id: "2241", answer: ",,CBA", question_title: "社会公德的特点是（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "2007", answer: "D", question_title: "李白笔下的“飞流直下三千尺，疑是银河落九天”指的是哪个风景区？（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2350", answer: "A", question_title: "课文《红楼梦（节选）》中《护官符》在文中起的作用是（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2357", answer: "C", question_title: "下列哪个故事不是古代民间故事？（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2364", answer: "D", question_title: "下列广告语中没有错别字的一项是（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2153", answer: "A", question_title: "慈爱之心是慈善事业的道德基础。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2047", answer: "A", question_title: "绿色消费的核心是实现可持续发展。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2391", answer: "A", question_title: "“学而时习之，不亦说乎”出自哪篇《论语》？（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2164", answer: "B", question_title: "不得使用伪、变造机动车号牌、行驶证，但临时借用其他机动车行驶证是可以的。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2167", answer: "A", question_title: "租赁期限6个月以上，应当采用书面形式。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2034", answer: "A", question_title: "小说的三要素：人物、情节、环境。（ ）"},
  {paper_id: "12", exam_question_id: "2393", answer: "A", question_title: "《红楼梦》中\"护官符\"上的四句话，是运用谐音和夸张的修辞方法，描写\"四大家族\"的财富和权势。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2181", answer: "B", question_title: "在诉讼过程中，必须要求律师打赢官司。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2337", answer: "B", question_title: "为了避免或减少“三废”污染，工厂首先要保证零排放。（）"},
  {paper_id: "14", exam_question_id: "2451", answer: "A", question_title: "法律咨询途径中的预约咨询一般为收费服务。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2420", answer: "A", question_title: "这座塔占地300平方米，高100米。运用了列数字说明方法。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2462", answer: "A", question_title: "法律是全体社会成员都要共同遵守的行为规范。尊法守法是我们的共同追求和自觉行动。（&nbsp;）"},
  {paper_id: "13", exam_question_id: "2243", answer: "D", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ed061670027.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "15", exam_question_id: "2089", answer: "D", question_title: "党的二十大报告指出，必须坚持（ &nbsp; ）是第一生产力、（ &nbsp; ）是第一资源、（ &nbsp; ）是第一动力，深入实施科教兴国战略、人才强国战略、创新驱动发展战略，开辟发展新领域新赛道，不断塑造发展新动能新优势。"},
  {paper_id: "12", exam_question_id: "1912", answer: "C", question_title: "下列句子中，加括号【】的成语使用正确的一项是( &nbsp; )"},
  {paper_id: "15", exam_question_id: "2104", answer: "A", question_title: "在我国，保证人民当家作主的国体和政体分别是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2280", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee5966f0091.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2472", answer: "B", question_title: "我国新冠病毒疫苗为全民免费提供，由国家公共财政保障。这表明（  &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1934", answer: "D", question_title: "下列句子中没有错别字的一项是（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2480", answer: "C", question_title: "劳动合同是劳动者和用人单位确立劳动关系、明确双方权利和义务的协议。订立劳动合同的主体是（  &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2426", answer: "A", question_title: "农业产品要到市场上销售，才能实现其价值，因此，最终决定农业生产的类型与规模的是（ &nbsp;  ）。"},
  {paper_id: "14", exam_question_id: "2488", answer: "A", question_title: "社会保险五大险种中最重要的险种是（ &nbsp;  ）。"},
  {paper_id: "15", exam_question_id: "2435", answer: "D", question_title: "电子工业、芯片制造工业属于（  &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2499", answer: "A", question_title: "李某将自己的楼房出租给赵某做生意。租期满后，赵某却以诸多理由长期占用房子， 拒不归还。李某应该（ &nbsp;  ）。"},
  {paper_id: "15", exam_question_id: "2436", answer: "C", question_title: "下面关于我国旅游资源的叙述，正确的是（ &nbsp;  ）"},
  {paper_id: "15", exam_question_id: "2438", answer: "A", question_title: "每年召开的全国两会是民意的荟萃，是群众意见、建议最为集中的表达．这体现了社会主义民主政治的本质特征是（  &nbsp;  ）"},
  {paper_id: "12", exam_question_id: "1988", answer: "A", question_title: "“路漫漫其修远兮，吾将上下而求索”是谁的名言? ( &nbsp; &nbsp; )"},
  {paper_id: "15", exam_question_id: "2134", answer: "A,B,D", question_title: "就业者的素质高低直接关系到就业的成败。（ &nbsp; &nbsp;）是就业者所必备的素质。"},
  {paper_id: "14", exam_question_id: "2238", answer: "A,B,C", question_title: "以下属于公民道德基本规范的是（ &nbsp; &nbsp;）。"},
  {paper_id: "14", exam_question_id: "2240", answer: "A,B,C", question_title: "以下属于公民的基本义务的是（ &nbsp; &nbsp;）。"},
  {paper_id: "14", exam_question_id: "2512", answer: "CD", question_title: "关于一般违法行为和犯罪行为的共同特点,说法正确的是（ &nbsp;  ）。"},
  {paper_id: "14", exam_question_id: "2522", answer: "BCD", question_title: "我国各地目前正在积极创建文明城市，下列表现符合文明有礼的市民标准是（ &nbsp;  ）。"},
  {paper_id: "14", exam_question_id: "2144", answer: "A", question_title: "“五爱”是社会主义社会人们应该遵循的五个最基本的道德规范。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2054", answer: "B", question_title: "凡是与用工单位建立稳定劳动关系的农民工都应通过个人缴费参加失业保险。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2066", answer: "B", question_title: "我国实行宗教信仰自由政策，要积极引导宗教与社会主义相适应。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2165", answer: "A", question_title: "机动车行经人行横道，应当减速行驶。遇行人通行，必须停车让行。在没有交通信号道路上，机动车要主动避让行人。（ &nbsp; ）"},
  {paper_id: "15", exam_question_id: "2074", answer: "A", question_title: "1894年，英国对清朝发动了甲午战争，清政府战败签订了《马关条约》，赔偿白银2亿两，并割让了台湾。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2172", answer: "A", question_title: "无效的劳动合同，从订立的时候起，就没有法律约束力。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2397", answer: "A", question_title: "普希金在写作《假如生活欺骗了你》时，正被沙皇流放，过着充满艰辛的流放生活，精神的压抑曾使诗人产生前程渺茫、壮志难酬的伤感。诗中就能体会出这种感伤之情。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2403", answer: "A", question_title: "《乡愁》诗人把乡愁比喻成邮票，是诗人的关于小时候的记忆。小小的邮票却寄托着深厚的感情和沉重的记忆。这样的比喻恰当有形象。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2454", answer: "B", question_title: "劳动者所有的劳动收入都属于工资的范围。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2405", answer: "A", question_title: "诗人把乡愁比喻成坟墓，是诗人的关于母亲的怀念的话，以及对于祖国的深刻的思念。两个个体被无情地分散开，流落在不同的境遇，作者顿生感念之情。感情的.深刻由此可见一斑。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2419", answer: "B", question_title: "他起床后，吃了早餐，然后去上班。采用的是描写的表达方式。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2455", answer: "B", question_title: "当自己的合法权益受到侵害时，只能通过诉讼的途径来解决。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2183", answer: "D", question_title: "在充满竞争的现代社会中，要正确对待竞争，应该保持的健康心态是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2265", answer: "A", question_title: "<p>已知球的半径为3，则该球的表面积为（ &nbsp; &nbsp; ）</p>"},
  {paper_id: "15", exam_question_id: "2097", answer: "A", question_title: "三百六十行，行行出状元”，是指要树立（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2216", answer: "B", question_title: "对于尚不触犯刑律的妨碍共安全的行为，要依照治安管理处罚条例，由（ &nbsp; ）予以制裁。"},
  {paper_id: "12", exam_question_id: "1918", answer: "A", question_title: "“床前明月光”是李白的千古名句，其中“床”指的是什么?( &nbsp; )"},
  {paper_id: "13", exam_question_id: "2288", answer: "A", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee8703600a5.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "1956", answer: "A", question_title: "“但使龙城飞将在，不教胡马度( &nbsp; &nbsp; )” "},
  {paper_id: "12", exam_question_id: "1968", answer: "A", question_title: "西湖的白堤的得名与哪位诗人有关? ( &nbsp; &nbsp;)"},
  {paper_id: "14", exam_question_id: "2514", answer: "CD", question_title: "近年来，许多城市将见义勇为工作与平安建设紧密结合，弘扬见义勇为精神，涌现出一大批匡扶正义、惩恶扬善的先进典型，点亮城市“正义之光”。这样做是因为（  &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2384", answer: "D", question_title: "选出和树林一直在唱着那首愉快的歌修辞方法相同的一项是（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2386", answer: "D", question_title: "能与“写鬼写妖高人一等”形成对偶的一项是（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2081", answer: "A", question_title: "中国古代四大发明中，纸的发明影响最为久远。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2037", answer: "A", question_title: "苏轼代表作《水调歌头·明月几时有》最后希望自己思念的人平安长久，不管相隔千山万水，都可以一起看到皎洁美好的明月。（ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2463", answer: "B", question_title: "因镇政府强行占用李某承包的土地，李某以镇政府为诉讼对象，向人民法院提起民事诉讼。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "1899", answer: "A", question_title: "下面宣传标语中表述不当的一项是（ ）"},
  {paper_id: "15", exam_question_id: "2087", answer: "C", question_title: "中国特色社会主义最本质的特征是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2254", answer: "D", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edc93f4003e.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2199", answer: "D", question_title: "王某住宿旅馆,在旅馆失窃贵重物品,旅馆侵害了王某的（ &nbsp; &nbsp;）。"},
  {paper_id: "12", exam_question_id: "1913", answer: "B", question_title: "下列加【】的成语使用不妥当的一项是（ &nbsp; &nbsp;）"},
  {paper_id: "13", exam_question_id: "2261", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0edfa32a0056.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2474", answer: "C", question_title: "关于我国接种新冠病毒疫苗，下列说法正确的是（  &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1962", answer: "C", question_title: "“爆竹声中一岁除，春风送暖入屠苏”，这里的“屠苏”指的是：( &nbsp; &nbsp;)"},
  {paper_id: "15", exam_question_id: "2430", answer: "D", question_title: "从青岛运输5万吨原油到上海，最合理的运输方式是（ &nbsp;  ）。"},
  {paper_id: "12", exam_question_id: "1974", answer: "B", question_title: "<p style=\"text-align: left;\">没有错别字的一句：（ &nbsp; &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2513", answer: "BD", question_title: "小王为讨薪，用爬高压线的方式威胁老板，虽要回欠薪，却因扰乱公共秩序，被公安机关拘留；小李则通过劳动争议仲裁顺利追回欠薪。两人不同维权方式告诉我们（ &nbsp;  ）。"},
  {paper_id: "14", exam_question_id: "2146", answer: "A", question_title: "守法是道德的底线，是对一个公民行为的最起码的规定。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2151", answer: "B", question_title: "奉献与索取成正比例，奉献越多，索取越多，即钱多多干，钱少少干，无钱不干。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2351", answer: "A", question_title: "课文《红楼梦（节选）》中\"因私枉法\"中的\"因\"的含义是（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2058", answer: "A", question_title: "中国特色社会主义民主的实质是人民当家做主。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2366", answer: "C", question_title: "下列成语正确的一项是（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2060", answer: "B", question_title: "全国人大和地方各级人大的代表由选民直接选举产生。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2444", answer: "A", question_title: "劳动者在试用期内的工资不得低于用人单位所在地的最低工资标准。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2399", answer: "A", question_title: "“问君能有几多愁？恰似一江春水向东流”运用了比喻、设问的修辞手法。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2197", answer: "A", question_title: "在民事诉讼中，举证责任的一般原则是（ &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "1927", answer: "A", question_title: "<p style=\"text-align: justify;\">“海内存知己，天涯若比邻”出自王勃的《送杜少府之任蜀州》，这首诗的题材是（ &nbsp; ）"},
  {paper_id: "13", exam_question_id: "2294", answer: "D", question_title: "<p>若正方体的边长变为原来的2倍，则体积变为原来的（ &nbsp; ）</p>"},
  {paper_id: "12", exam_question_id: "1969", answer: "D", question_title: "<p style=\"text-align: justify;\">《红楼梦》是我国古代着名的长篇小说之一，下列哪个不是它的别名：( &nbsp; &nbsp;)"},
  {paper_id: "12", exam_question_id: "1983", answer: "A", question_title: "下面语句排列最恰当的是（ &nbsp; &nbsp;）<br><p style=\"text-align: justify;\">①用一根思想的线串起生活的珍珠，珍珠才不会遍地乱滚 &nbsp; <p style=\"text-align: justify;\"> ②散文虽“散”而不乱<p style=\"text-align: justify;\"> ③全靠思想把那一切材料统一起来<p style=\"text-align: justify;\"> ④ 这才成为整齐的珠串"},
  {paper_id: "12", exam_question_id: "1986", answer: "A", question_title: "下列句子中，画线成语使用正确的一句是（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2019", answer: "A", question_title: "“写鬼写妖高人一筹,刺贪刺虐入木三分”是对蒲松龄《聊斋志异》的高度评价。（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2022", answer: "A", question_title: "<p style=\"text-align: justify;\">通知可粗分为公文类通知和事务类通知。公文通知多用于单位内布置工作、传达事情、召集会议等。（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2030", answer: "A", question_title: "苏轼的代表作之一《水调歌头·明月几时有》通过对月宫仙境的想象，在一种极富神秘色彩的探索和思考中，表现自己的思想矛盾与波折、人生体验与认识，具有浪漫主义色调和超旷飘逸的风格。（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2412", answer: "A", question_title: "“问君能有几多愁？恰似一江春水向东流”，把“愁”比做“一江春水向东流”，突出了“愁”的深重、强烈和无穷无尽。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2207", answer: "C", question_title: "关于节俭和消费，说法正确的是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2274", answer: "C", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee403200081.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "14", exam_question_id: "2494", answer: "A", question_title: "法律意义上的“老赖”，一般是指在民事商业领域中的一类债务人，其拥有偿还到期债务的能力，但是基于某种原因拒不偿还全部或部分债务；主观上，“老赖”有故意拖延履行债务的恶意，客观上拒不履行到期债务。这种人（  &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2353", answer: "C", question_title: "下面是课文《红楼梦（节选）》中“护官符”与王府对应的是哪一句？（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2521", answer: "DC", question_title: "公平正义是人类追求的永恒目标，是法治社会的核心价值。下列事件符合坚守公平要求的是（   &nbsp; ）。"},
  {paper_id: "12", exam_question_id: "2375", answer: "B", question_title: "下列句中像字的作用与其他三句不同的一句是 (&nbsp;)"},
  {paper_id: "12", exam_question_id: "2410", answer: "A", question_title: "“问君能有几多愁？恰似一江春水向东流”“君”指的是作者自己。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "1895", answer: "D", question_title: "下列广告语中没有错别字的一项是 （ &nbsp;）"},
  {paper_id: "14", exam_question_id: "2190", answer: "D", question_title: "山东冠县一小区多辆私家车占用消防通道,导致出警的消防车无法进入。情急之下,多名居民将占位的私家车掀翻清出道路,火场得到及时扑救。该私家车的行为（ &nbsp; ）。"},
  {paper_id: "15", exam_question_id: "2061", answer: "A", question_title: "我国的村民委员会是村民的自治组织，不是国家机关。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2036", answer: "A", question_title: "“桃花仙人种桃树，又摘桃花换酒钱”“桃花仙人”指的是陶渊明（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2404", answer: "A", question_title: "诗人把乡愁比喻成船票，是诗人对于自己成年后人生的一段记忆，诗人在其中有许多辛酸的记忆和故事，每当作者回想起来就会感到无限的怅惘和怀念。（&nbsp;）"},
  {paper_id: "15", exam_question_id: "2094", answer: "D", question_title: "近年来，越来越多的人开始利用网络平台约车、订票、购物等，这类“分享经济”模式，根本上有利于（ &nbsp; &nbsp;）。"},
  {paper_id: "14", exam_question_id: "2211", answer: "B", question_title: "陈某为试探丈夫，藏匿儿子、谎称其失联，报警并在互联网上求助，后被人民法院以编造、故意传播虚假信息罪判处刑罚。这告诫我们（ &nbsp; ）。 &nbsp;"},
  {paper_id: "15", exam_question_id: "2427", answer: "C", question_title: "我国南方和北方地区的分界线是（  &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2290", answer: "B", question_title: "<p>下列各式中错误的是（ &nbsp; &nbsp; ）</p>"},
  {paper_id: "12", exam_question_id: "2361", answer: "D", question_title: "下列词语中没有错别字的是 （&nbsp;&nbsp;）"},
  {paper_id: "14", exam_question_id: "2209", answer: "B", question_title: "小胡通过微信给一名货主转账，因误操作而将帐转给另一人罗某。小胡要求罗某退款，而罗某拒绝退款。对此，下列说法或做法正确的是（ &nbsp; ）。"},
  {paper_id: "13", exam_question_id: "2291", answer: "D", question_title: "<img src=\"http://cj.nbjyzx.net:10000/oss-ysyzy/local/cloud_crjy/202603/402881879d0e87f1019d0ee934b000ab.png\" style=\"max-width:100%;\" contenteditable=\"false\"/><br/>"},
  {paper_id: "12", exam_question_id: "2000", answer: "C", question_title: "“己所不欲，勿施于人”孔子这句话反映的是（ &nbsp; )"},
  {paper_id: "12", exam_question_id: "2009", answer: "A", question_title: "“红娘”是哪部作品中的人物？（ &nbsp; &nbsp;）"},
  {paper_id: "12", exam_question_id: "2409", answer: "A", question_title: "《虞美人》中“雕栏玉砌应犹在，只是朱颜改”，“朱颜改”三字，既可以理解为古国宫殿的颜色已经陈旧，也可以理解为旧时宫女的容貌已经衰老、憔悴，又可理解为原为故国君主的词人自己已经沦为“阶下囚”而憔悴不堪，更可以理解为国家易主，江山变色。（&nbsp;）"},
  {paper_id: "14", exam_question_id: "2221", answer: "C", question_title: "2020年5月28日，十三届全国人大三次会议表决通过了《中华人民共和国（ &nbsp; ）》，自2021年1月1日起施行。"},
  {paper_id: "12", exam_question_id: "1977", answer: "A", question_title: "“脏兮兮的浅绿色毛围巾一直耷拉到膝盖，膝上放着一个大包袱。”运用的表达方式是（ &nbsp; &nbsp;）"},
  {paper_id: "12", exam_question_id: "1938", answer: "C", question_title: "<p style=\"text-indent: 18pt;\">依次填入下面空格中的词语，最恰当的一项是（ &nbsp; ）<p style=\"text-indent: 18pt;\">①六七十岁的老人尚且这样认真地学习电脑，______我们这些年轻学生呢？<p style=\"text-indent: 18pt;\">②人类基因草图的绘制成功，______着生命科学的研究又进入了一个新阶段。<p style=\"text-indent: 18pt;\">③中国政府_____美国政府改变立场，立即采取有效举措拯救中东和平进程。<p style=\"text-indent: 18pt;\"><br>"},
  {paper_id: "12", exam_question_id: "1954", answer: "A", question_title: "燃放烟花最佳的气象条件:有较多分散性低云、碎积云，云底高度在1000米左右，有一定的水汽，相对温度70%左右，风力小于3级。下列诗句描述的天气中最适合欣赏烟花的是（ ）"},
  {paper_id: "12", exam_question_id: "1967", answer: "B", question_title: "<p style=\"text-align: justify;\">《诗经》是我国第一部诗歌总集，《诗经》里面包括多少首诗? ( &nbsp; &nbsp;)"},
  {paper_id: "12", exam_question_id: "2021", answer: "A", question_title: "<p style=\"text-align: justify;\">演讲也称演说，是在公开的场合做口头介绍，发表个人的观点，阐述人生的经验，带有宣传鼓动性。（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2039", answer: "A", question_title: "<p style=\"text-align: justify;\">写失物招领，要注意交待清楚领取的具体方式，或注明发文者的详细地址、联络方式。（ &nbsp;）"},
  {paper_id: "12", exam_question_id: "2414", answer: "A", question_title: "“学而不思则罔，思而不学则殆”是孔子所提倡的一种读书及学习方法。（&nbsp;）"},
  {paper_id: "12", exam_question_id: "2388", answer: "D", question_title: "下面的句子都使用了修辞方法，找出最能增强气势，突出这种作风危害的一句是（ &nbsp;）"},
  {paper_id: "15", exam_question_id: "2057", answer: "A", question_title: "在征地过程中要维护被征地农民的知情权、参与权、监督权和申诉权，解决好被征地农民的就业、住房和社会保障问题。（ &nbsp; ）"},
  {paper_id: "14", exam_question_id: "2148", answer: "A", question_title: "反映人与环境之间关系的公德叫人类环境公德。（ &nbsp; ）"},
  {paper_id: "12", exam_question_id: "2379", answer: "C", question_title: "与例句的修辞方法完全相同的一组是（&nbsp;）例句:淡黑的起伏的连山，仿佛是踊跃的铁的兽脊似的，都远远地向船尾跑去了。<br>①野花遍地是:杂样儿，有名字的，没名字的，散在草丛里像眼睛，像星星，还眨呀眨的。<br>②重庆的夜，微波荡漾的江面上倒映着万家灯火，盏盏点点，这是自由诗，这是交响乐。<br>③纺车总是安安稳稳地呆在那里，像着陆停驶的飞机，一声不响，仿佛只是在等待。<br>④就凭这些绿的精神，水也不忍得冻上，况且那些长枝的垂柳还要在水里照个影儿哩!"},
  {paper_id: "15", exam_question_id: "2345", answer: "A", question_title: "你所在的企业拖欠你的工资，你可以找企业工会出面协调。（&nbsp;）"},
  {paper_id: "12", exam_question_id: nil, answer: "D", question_title: "新冠疫情发生以来，在以习近平同志为核心的党中央坚强领导下，始终把人民群众生命安全和身体健康放在第一位，全面提高依法防控、依法治理能力，为疫情防控工作提供有力法治保障。上述体现的发展思想和治理国家的基本方略分别是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2195", answer: "D", question_title: "“珍爱信用记录，享受幸福人生”。关于个人信用记录，以下看法不正确的是（ &nbsp; ）。"},
  {paper_id: "14", exam_question_id: "2457", answer: "A", question_title: "法律是最刚性的社会规则，不违法是人们行为的底线。（&nbsp;）"}
])
